### ISSUE TITLE
Does not launch a VM when there are spaces in its path

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#1]
reported by Skip Lentz:

On OSX, I renamed the application from "Pharo.app" to "Pharo Launcher.app" with a space in the middle.

"PhLImage>>lauch:" then uses OSProcess with a command containing unescaped spaces.

**Comment by nicolaihess** [comment]
With the fix in
PharoLauncher-Core-SkipLentz.79
the command for OSProcess in 
PhLImage>>launch: aFullPathString
does not work on windows.

**Comment by Balletie** [comment]
Ugh.. I was afraid of that. We need to find a way for this.

**Comment by cdlm** [comment]
oops, fat fingers…

**Comment by marianopeck** [comment]
Hi Damien. Here is my user :)

**Comment by marianopeck** [comment]
How can I load PharoLauncher into my Pharo 40 fresh image?

**Comment by DamienCassou** [comment]
On December 21, 2015 5:55:07 PM GMT+01:00, marianopeck <notifications@github.com> wrote:
>How can I load PharoLauncher into my Pharo 40 fresh image?

You load the configuration in smalltalkhub:Pharo/PharoLauncher


-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by StephanEggermont** [comment]
Seems to be working now using version 87

**Comment by Balletie** [comment]
Does it work on Windows now too?

**Comment by StephanEggermont** [comment]
Vincent confirmed it on Windows

**Comment by Balletie** [comment]
Confirmed working on OS X too, also with spaces in the path. Can be closed in my opinion @DamienCassou.

**Comment by DamienCassou** [comment]
Thanks guys
