### ISSUE TITLE
When image is created, auto select it 

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#10]
Reported by Ben Coman:

I'd like to ask your help with a feature I've been wanting for a while.  I spent half a day trying but just can't work it out how to get this...

I regularly have 100 images listed. I should clean up more regularly, but even so, I still have many.  Many of the builds have a virgin (effectively read-only) version I use for bisecting to find when a problem was introduced; and case I work on may end up with half a dozen images as I test various ideas and that the slice loads back in cleanly.

So when I create an image, sometimes it gets "lost".  Maybe I did a typo in the name, or it just takes a while to pinpoint it in the list. 

What I'd really like a lot is that when the image is created, it is auto-selected.  So its easy to tell which image was created.

I had great difficulty trying to find my way from the context handed to the PhLCommands back to the list.

Have you got any pointers?

**Comment by DamienCassou** [comment]
Comment by Ben Coman:

Actually it would be good if the same happened when an image was renamed or copied.

Of course, I'd like to do as much as I can, once I know how to set the list selection from a PhLCommand.

**Comment by DamienCassou** [comment]
Comment by Nicolai Hess

This would be a great addition. The way from the PHLCommands to the view
goes through a simple ValueChanged announcement.
PhLTitledTreeModel>>#refresh is called if the repository(or its contents) changed.

We can add less generic Announcement by creating
ImageAdded/ImageRemoved/ImageRenamed announcements and call them in
for example in PhLDirectoryBasedImageRepository>>#extractTemplate:to:
(instead of self contentsChanged, call self imageAdded, which would then
announce an appropiate announcement ...).

But I couldn't find a way to actually change the selection on the tree!
The PhLTitledTreeModel is subclass of TreeModel there must be a way to
change the selected item, but I don't know how.

**Comment by demarey** [comment]
done in latest (dev) version
