### ISSUE TITLE
No way to rename a local template

### ISSUE THREAD

**Issue by philippeback** [pharo-project/pharo-launcher#103]
![image](https://user-images.githubusercontent.com/2128441/39677796-6a38faa0-5181-11e8-9bff-f6ac5b7ec0b3.png)

**Comment by VincentBlondeau** [comment]
Name: PharoLauncher-Core-VincentBlondeau.189
Author: VincentBlondeau
Time: 24 May 2018, 2:02:57.561507 pm
UUID: a3b37bb6-5b29-0d00-be1c-3127059c4b2c
Ancestors: PharoLauncher-Core-VincentBlondeau.188

Add the possibility to rename a local template
