### ISSUE TITLE
Wrong package cache

### ISSUE THREAD

**Issue by Ducasse** [pharo-project/pharo-launcher#105]
When donwloading a fresh pharo 70 image I always gets the following MC cache MCCacheRepository(/Users/ducasse/Documents/Pharo/images/Pharo70-Iceberg7/pharo-local/package-cache)

Which is plain wrong

**Comment by Ducasse** [comment]
FileSystem workingDirectory 
>>> File @ /Users/ducasse/Documents/Pharo/images/AA2

FileLocator imageDirectory resolve
>>> File @ /Users/ducasse/Documents/Pharo/images/AA2

**Comment by VincentBlondeau** [comment]
Hum...
it is working on my side:
![image](https://user-images.githubusercontent.com/4706329/40513966-4d6ebcdc-5f5c-11e8-8ace-6dd515bf083f.png)

I just took the Official distributions/Pharo 7.0 - 32bit (dev version) and run it.

Did I miss a step to reproduce your bug?

**Comment by Ducasse** [comment]
May be this is something in my settings but I do not see why


StartupPreferencesLoader default executeAtomicItems: {
	StartupAction 
		name: 'Git Settings' 
		code: [ 
			Stdio stdout
				cr; nextPutAll: 'Setting the ssh credentials'; cr.
			Iceberg enableMetacelloIntegration: true.
			IceCredentialsProvider useCustomSsh: true.
			IceCredentialsProvider sshCredentials
					username: 'git';
					publicKey: '/Users/ducasse/.ssh/id_rsa.pub';
					privateKey: '/Users/ducasse/.ssh/id_rsa'.
			IceCredentialsProvider 
				plaintextCredentials: (IcePlaintextCredentials new username: 'Ducasse'; password: 'xxxx' ; yourself ).
			IceLibgitRepository shareRepositoriesBetweenImages: true;
 		sharedRepositoriesLocation: '/Users/ducasse/Workspace/FirstCircle/ActiveResearch/Pharo/PharoCodeBase' asFileReference.
			Stdio stdout 
				cr; nextPutAll: 'Finished'; cr ]. 
}.

**Comment by Ducasse** [comment]
Which version of launcher are you using?

**Comment by demarey** [comment]
Checked with Stephane directly. Not a bug related to the Launcher nor Pharo.
Mess with some startup script.
