### ISSUE TITLE
Import could work if we select the parent folder of an image

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#106]
During the import, at first, I found it unclear if I should select the folder containing the image or directly the image in the file select window.

Maybe if we select a folder containing an image of the same name we could import this image instead of failing silently? 

Or prompt a dialog to the user "Should we import XXX.image?"?

**Comment by jecisc** [comment]
Ok. But in that case, just an #inform: would be cool. Something saying "Selected file is not an image. Import canceled."

**Comment by demarey** [comment]
ok for the notification. ;)

**Comment by philippeback** [comment]
As I have several https://github.com/Pharophile/HOImageSaver versions in a folder, it would be problematic.

I usually save versions and at one point resave with the name used by the launcher. It works and I can keep stuff around in case I need to go back to a quick snapshop. On the disk usage front, non issue here, this thing is on a 4TB disk (Pharo can eat quite a lot of disk this way).

**Comment by jecisc** [comment]
If you wish I can do it later.

**Comment by jecisc** [comment]
@demarey If the fix is fine with you we can close the issue.

**Comment by demarey** [comment]
@jecisc Ok. Thanks for the contribution

**Comment by jecisc** [comment]
That's weird when I tried it worked. And I was not in dev mode. I opened the browser and Monticello via the shortcuts.

**Comment by demarey** [comment]
hum. I tested again in a clean environment and it's ok.
Thanks
