### ISSUE TITLE
Unable to add a description for the image using the Launcher UI

### ISSUE THREAD

**Issue by philippeback** [pharo-project/pharo-launcher#107]
It seems that I do have to edit a local file in a folder to get a description.

It would be great to be able to do so from the LauncherUI.

**Comment by demarey** [comment]
What kind of description do you talk about?

**Comment by demarey** [comment]
oh!
You made me discover a Pharo Launcher feature!
Right, we must have a command to add the description from the interface.

**Comment by philippeback** [comment]
:1st_place_medal: I am using that thing for real, it is cool :-)
Next step: make my own image flavor on the jenkins.

**Comment by demarey** [comment]
@olivierauverlot implemented it last Friday during Pharo sprint.

-----
Name: PharoLauncher-Core-ChristopheDemarey.189
Author: ChristopheDemarey
Time: 28 May 2018, 3:38:21.396439 pm
UUID: 7537d3f7-a529-0d00-af19-ffd00ca9b49f
Ancestors: PharoLauncher-Core-ChristopheDemarey.188

Unable to add a description for the image using the Launcher UI
https://github.com/pharo-project/pharo-launcher/issues/107
