### ISSUE TITLE
Won't re-launch after launching an Image that remains open on OSX

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#11]
Reported by Tim Mackinnon

On OSX, when you launch an image using the .app "all in" build, you can only run one instance of the image. Trying to launch it again, just refocuses on the already running instance. (Its not clear whether this is a change in OSX Mavericks or something that has changed in the VM).

A proposed solution is to let PharoLauncher specify an alternate VM to use for launching. This has the nice side effect that you can use Launcher to test with alternate VM's.

**Comment by DamienCassou** [comment]
Comment by Tim Mackinnon

Fix submitted to PharoLauncher/main

**Comment by DamienCassou** [comment]
Comment by Damien Cassou:

Thanks, I like that we can now specify a VM instead of using the default one. However, your fix does only solve the problem for advanced users who downloaded a separate VM and configured the launcher. I would prefer a fix that applied to new users as well.

**Comment by demarey** [comment]
no more relevant
