### ISSUE TITLE
Import in Launcher moves the files

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-project/pharo-launcher#117]
if you import an image in the Launcher, the related files are moved to the new location. I personally expected that they will be copied only.

**Comment by VincentBlondeau** [comment]
![image](https://user-images.githubusercontent.com/4706329/41749859-bf25a670-756d-11e8-9cb1-757efb2ff2cc.png)
It is now especially written that the files will be moved. Do you still want a import with a file copy option instead of a move file?

**Comment by pavel-krivanek** [comment]
closing, thank
