### ISSUE TITLE
Code cosmetic (readability) PRCocoonConfiguration>>export:

### ISSUE THREAD

**Issue by bencoman** [pharo-project/pharo-launcher#12]
While tracing through Pillar (from Ecstatic) I found this hard to read i.e. even after I'd understood it, I had to decipher it anew each time I tried to read it.

PRCocoonConfiguration>>export: configurationName
	self log: 'Exporting ', configurationName.
	((self subConfigurationNamed: configurationName)
		ifNil: [ self findDefaultConfigurationNamed: configurationName ]
	) export.
	self log: 'End of exporting ', configurationName

Splitting with a named variable makes it more obvious...

PRCocoonConfiguration>>export: configurationName
	| subconfig |
	self log: 'Exporting ', configurationName.
	subconfig := ((self subConfigurationNamed: configurationName)
		ifNil: [ self findDefaultConfigurationNamed: configurationName ]).
	subconfig export.
	self log: 'End of exporting ', configurationName

**Comment by bencoman** [comment]
Uploaded  Pillar-ExporterCore-BenComan.248

**Comment by DamienCassou** [comment]
thanks Ben. Could you please open the issue on https://github.com/pillar-markup/pillar/issues instead?
