### ISSUE TITLE
The Run without settings icon looks like a funny grey/white blob (missing alpha correction)

### ISSUE THREAD

**Issue by macta** [pharo-project/pharo-launcher#122]
The icon for running an image without loading the settings, looks like a funny gray and white blob (on OSX - not sure about windows).

The intent was just to invert the colours, so the green triangle is just grey - however simply grayscaling without alpha causes it to look strange. (simple fix is to use #grayscaleWithAlpha)

**Comment by macta** [comment]
This is fixed in the following contribution
Name: PharoLauncher-Core-TimM.174
Author: TimM
Time: 18 June 2018, 6:11:54.416337 pm
UUID: d9433566-4f2b-0d00-85be-afca09965ccd
Ancestors: PharoLauncher-Core-TimM.173

**Comment by demarey** [comment]
Thanks for this contribution
