### ISSUE TITLE
The status bar of the Launcher is broken, so can't easily show image descriptions

### ISSUE THREAD

**Issue by macta** [pharo-project/pharo-launcher#123]
There is a status bar component on the launcher, but when you try to put something in it (like the image description - currently read from a "description.txt" file) nothing appears.

It looks like spec is quite finicky when you put a table in a component (and there is a table to hold the toolbar buttons next to the textual status bar). The fix is to rejig the layout to use a table completely.

**Comment by macta** [comment]
The status bar is fixed in this contribution (and its then trivial to add the existing description functionality to the status bar when you click on an item)

see:
Name: PharoLauncher-Spec-TimM.70
Author: TimM
Time: 18 June 2018, 5:32:00.928101 pm
UUID: 5e888bd7-4e2b-0d00-85bb-537409965ccd
Ancestors: PharoLauncher-Spec-TimM.69


Name: PharoLauncher-Core-TimM.172
Author: TimM
Time: 18 June 2018, 5:34:46.055084 pm
UUID: 6a2b63e1-4e2b-0d00-85bc-0fed09965ccd
Ancestors: PharoLauncher-Core-TimM.171

**Comment by demarey** [comment]
Thanks for this contribution!
