### ISSUE TITLE
New versions of Launcher don't remember old settings

### ISSUE THREAD

**Issue by macta** [pharo-project/pharo-launcher#127]
If you adjust the image and vm settings to a new location, they aren't preserved when you load an new version of launcher (and its a pain to have to go and reset them). We should be able to persist this information somewhere - pharo has a mechanism for storing settings - we should be alble to use it?

**Comment by demarey** [comment]
Did you notice that you already can persist Pharo Launcher settings from the settings menu?
These settings are then available for new launcher versions.

**Comment by macta** [comment]
Ah - I didn’t think about the Pharo settings applying to Launcher even thought I was writing about them. Silly me.

Of course for a new user, not sure how they would figure it out - but maybe I can update the readme on github as there are other more useful things we can spend time on.

Tim

**Comment by demarey** [comment]
If you did not find it, then it is not obvious.
Yes, maybe some documentation on the feature would help.
I did not test, but Pharo theme (dark / white) is also a Pharo Launcher setting. Maybe it could solve your other issue.

**Comment by macta** [comment]
I’ll try it out - for the white/dark not sure why it changed between 1.1 and 1.2 but settings might be the cause.

**Comment by macta** [comment]
I can confirm that having saved my settings in V1.2, when I installed v1.3 on top it did correctly restore my vm and image directories - however there still remains a string issue with the theme (see separate issue).

So I think the only real thing here is to perhaps make it a bit clearer how the settings work.

**Comment by macta** [comment]
I’ll raise a new issue about making it easier to find/understand that settings can be saved.
