### ISSUE TITLE
Launcher always reverts to White theme on startup

### ISSUE THREAD

**Issue by macta** [pharo-project/pharo-launcher#128]
Not sure what happened in the 1.2 release, but launcher always reverts to the white theme - both on a fresh install as well as when you exit dev mode. You can set it to dark, but if you go into dev mode and then exit - it still reverts back to white (even though the setting is dark) This wasn't the behaviour in 1.1

**Comment by demarey** [comment]
Could you tell me if this issue is valid if you set it in dark theme, store settings, then exit and start Pharo Launcher?

**Comment by macta** [comment]
I don't even have to explicitly store the settings - I just need to go into settings, pick the dark theme and then close them and then it stays that way.  But if I go into dev mode and back out, it reverts to white even thought the dev mode was using the Dark theme and the setting was showing Dark before I untick dev mode (it didn't do this in V1 - which started out dark in the first place - so maybe some default has changed? I haven't knowingly saved any settings for PL up to this point).

I've now also tried pressing "save settings" and it says it saved something, but when I go in and out of dev mode it still reverts to white. So it seems like the settings store/retrieve has changed somehow?

**Comment by macta** [comment]
Just installed 1.3, and when I first launched it, it started up with the Dark Theme (v1.2 started with a white theme, but v1.1 started with Dark).

However, jumping into dev mode and then back into user mode seemed to kick it back into the white them again.

**Comment by VincentBlondeau** [comment]
Indeed the theme settings are reset when exiting the dev mode

**Comment by VincentBlondeau** [comment]
But, it is not an important bug in the measure where you do not switch everyday to dev mode (actually as an user you should not do it)

**Comment by macta** [comment]
It got introduced in 1.2 - and on that build it caused the first launch of PL to be white (which looks terrible). I'm not really clear now if 1.3 is loading my saved settings to get that initial black - I need to test on a new machine.

I agree its not a mega bug though

**Comment by capsulecorplab** [comment]
I have the same issue; dark theme setting doesn't persist when relaunching pharo launcher.

It may not be a mega bug, but it hurts my eyes nonetheless.

**Comment by demarey** [comment]
Hi,
I just did some changes to allow theme change. When the theme setting is changed, it does not reopen all windows but now all UI components adapt to the theme change. To have the theme change persistent, you need to click on the `store settings` button in the settings window.
A preview version will be available here: https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/dev/200/

<blockquote><img src="/pharo-ci-jenkins2/static/0cd69064/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/dev/200/">PharoLauncher-Pipeline » dev #200 [Jenkins]</a></strong></div></blockquote>
