### ISSUE TITLE
Warning that appear everytime when you run a 32 bits image in a 64 bits VM PharoLauncher

### ISSUE THREAD

**Issue by SergeStinckwich** [pharo-project/pharo-launcher#129]
I download the 64 bits VM for macOS. Everytime I run a 32 bits image, I have a warning that using a 32 bits images, require a 32 bits VM. And then when I select yes, everything works. Why having this warning everytime ? One idea is to restrict this warning to Linux platform.

**Comment by badetitou** [comment]
Why not having another option "don't show me this again".
Because as a Linux developer, once I've installed the 32bits libs, I don't expect to see the warning message again.

**Comment by demarey** [comment]
I implemented a setting to disable/enable warning.
I also added a checkbox on the warning dialog box that will set the setting value.
I still need to test it now.

------------
Name: PharoLauncher-Core-ChristopheDemarey.198
Author: ChristopheDemarey
Time: 21 June 2018, 12:01:58.260537 pm
UUID: 154929be-852b-0d00-95ac-d0f803139e04
Ancestors: PharoLauncher-Core-ChristopheDemarey.197

Add a setting to disable image architecture warning.
See https://github.com/pharo-project/pharo-launcher/issues/129

**Comment by demarey** [comment]
Works as expected

**Comment by seandenigris** [comment]
@demarey The original request to disable completely for non-Linux systems seemed to be an important one. Also, why not try to launch the image and only show the dialog if it fails?

**Comment by seandenigris** [comment]
PharoLauncher-Core-SeanDeNigris.200 - Only Warn RE 32-bit on Linux 64

**Comment by demarey** [comment]
As I explained on the ML, the goal of this warning is also to inform people that they use 32-bit images on a 64-bit system. I would be tempted to keep it as it is now in v1.3. Did you try it? Do you still find it annoying?

**Comment by seandenigris** [comment]
Personally, I can live with the setting, but I'd like to understand the intention better. 

What is the value of the information? Are we trying to move people away from 32-bit images? I always stayed with 32-bits because 64-bit images seemed buggy and experimental. Is that no longer the case? My sense is that there will be valid use cases to continue working with 32-bit images, so maybe the warning will do more harm than good? 

Also, the message is very Linux-specific…

**Comment by demarey** [comment]
> Are we trying to move people away from 32-bit images? I always stayed with 32-bits because 64-bit images seemed buggy and experimental. Is that no longer the case? 
It was my intention. Maybe it is a bit too early? Also with #133, it already provides such information. I think that we can only warn on Linux for now. I will just update the fix to do not raise the warning instead of ignoring it.

**Comment by demarey** [comment]
Name: PharoLauncher-Download-ChristopheDemarey.15
Author: ChristopheDemarey
Time: 28 June 2018, 11:52:35.407701 am
UUID: 7575806d-122c-0d00-9bb1-9e4a07e6c2c1
Ancestors: PharoLauncher-Download-ChristopheDemarey.14

only warn on architecture if on Linux 64-bit
https://github.com/pharo-project/pharo-launcher/issues/129
