### ISSUE TITLE
[Enh]: Image Widget - Simplify Timestamp & Add Template Column

### ISSUE THREAD

**Issue by seandenigris** [pharo-project/pharo-launcher#130]
PharoLauncher-Core-SeanDeNigris.199 & PharoLauncher-Spec-SeanDeNigris.72

![screenshot 2018-06-24 10 17 18](https://user-images.githubusercontent.com/184176/41819959-d8a0511e-7797-11e8-8b7b-70673e9225e4.jpeg)

**Comment by seandenigris** [comment]
![screenshot 2018-06-24 10 17 18](https://user-images.githubusercontent.com/184176/41819958-cd4217b2-7797-11e8-815c-1453ec4ac2c8.jpeg)

**Comment by demarey** [comment]
Great! eager to try it
Thanks!
