### ISSUE TITLE
Add a "Pharo version" column

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#132]
Now when we launch an image the first step is to generate a file with the version of Pharo. 

We could use this file to display the Pharo version of our images. Like that we would not need to add it in the name. 

If nobody complains I might do it when I'll have some time.

**Comment by demarey** [comment]
Good idea!
I also just added an 'Arch' column to indicate whether it is a 32-bit or a 64-bit image. See #133

**Comment by demarey** [comment]
I think it is now time to only show the images table on the main window. We have now many information to display and the UI becomes a bit cluttered.
We discussed with @guillep to have a + button that will allow you to create new images from templates. It would open a new window with the current list of templates (or a better UI).
I would like to have the Pharo version as a separate column and not mixed with the arch.

**Comment by macta** [comment]
I wasn't sure at first - but I'm warming to the idea. On first launch we should show some type of help to get people started (or show the new project/image/whatever we call it window)

**Comment by bencoman** [comment]
There is currently a "Template" column that does a reasonable job of indicating the Image version.  Is that sufficient?

**Comment by demarey** [comment]
done in latest (dev) version
