### ISSUE TITLE
Add an arch column for images

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#133]
Pharo Launcher should provides a way to get the architecture information of an image: is it 32 or 64 bit?

**Comment by demarey** [comment]
Name: PharoLauncher-Spec-ChristopheDemarey.73
Author: ChristopheDemarey
Time: 27 June 2018, 9:36:39.163768 am
UUID: acad8269-fc2b-0d00-9335-866a05b73768
Ancestors: PharoLauncher-Spec-SeanDeNigris.72

Add an arch column

**Comment by jecisc** [comment]
Maybe it could go with my proposition of Pharo version? Display "P7-32bits" or "P6-64bits"

**Comment by jecisc** [comment]
I just saw you though the same :) thank you!
