### ISSUE TITLE
Cyclic dependency between PharoLauncher-Core and PharoLauncher-Download

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-project/pharo-launcher#146]
There is a cyclic dependency between PharoLauncher-Core and PharoLauncher-Download because of PhLError and PhLTObject

**Comment by demarey** [comment]
I do not like this PhLTObject. I do not think traits are needed for PharoLauncher

**Comment by pavel-krivanek** [comment]
I have the same impression

**Comment by guillep** [comment]
Fix in #147
