### ISSUE TITLE
Use OSSubprocess

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-launcher#155]

**Comment by jecisc** [comment]
No. It works on OSX and Linux but not on Windows yet.

**Comment by macta** [comment]
So this issue is parked until it supports Windows (and similarly I can’t use it on Exercism either)

**Comment by jecisc** [comment]
Currently the launcher uses OSProcess for unix and ProcessWrapper for windows.

I guess this issue is about replacing OSProcess to OSSubProcess. (And only later ProcessWrapper aswell when the support will be available in OSSubProcess)

**Comment by guillep** [comment]
Yes, its exactly that. We will still use ProcessWrapper for windows until an overcoming solution comes to light.

**Comment by demarey** [comment]
Done
