### ISSUE TITLE
Provide a way to update / remove VMs

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#172]

**Comment by demarey** [comment]
For now, there is no way to manage downloaded VMs by Pharo Launcher. PL should provide a small UI that list available VMs and offer an update and a remove action. The update action is important for the latest VM for instance.

**Comment by jecisc** [comment]
This would be cool. What would be even cooler is to have a notification "A new stable VM is available for Pharo 6.1. <link>Click here to update.</link>" when a new stable is promoted. 

But I don't know how hard it would be. It would require Network but the launcher already require it for download.

**Comment by demarey** [comment]
done in PR #235
