### ISSUE TITLE
PhLImage relies directly on Smalltalk  vmDirectory. This has at least two problems. The coupling by singleton and the fact that pharo 6 and 7 respond differently to it

### ISSUE THREAD

**Issue by sbragagnolo** [pharo-project/pharo-launcher#176]

**Comment by sbragagnolo** [comment]
cleanLDLibraryPath
	^ self currentLDLibraryPathes reject: [ :path | path asByteArray utf8Decoded = Smalltalk vmDirectory ]

**Comment by demarey** [comment]
We need to get the Pharo Launcher VM directory path to remove it from LD_LIBRARY_PATH on Linux. If not, environment is corrupted: you run a VM trying to find its libraries in the folder of another VM. Of course, it does not work
