### ISSUE TITLE
Pharo Launcher kills your development environment if you save your image

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-launcher#177]
It closes all your windows and tries to load settings that come from nowhere.

Moreover this shows an issue in Pharo's exception management on startup with notifications.

**Comment by demarey** [comment]
it is probably caused by PharoLauncher startup actions. Were you in development mode?
Pharo Launcher has its own settings stored in a PharoLauncher folder.

**Comment by guillep** [comment]
I know it's because of PharoLauncher startup actions. But It cannot continue like that, It kills your productivity. I just cloned the launcher and It's like that so the default value is wrong.

**Comment by guillep** [comment]
I'll for now disable all startup actions. Because the management of settings is also messing in my machine (where I have no settings!)

**Comment by demarey** [comment]
I also do not like how *development mode* works. I never took time to fix it but we should find a better way to switch from development to production mode and vice-versa.

**Comment by VincentBlondeau** [comment]
Also the settings should not be loaded if the image is not deployed
