### ISSUE TITLE
Bless the .dmg

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#21]
There is a [Jenkins job](https://ci.inria.fr/pharo/view/all/job/Launcher-Mac/) taking care of building a `.dmg` file to facilitate installation of the launcher. But this dmg is not recognized by Apple which means users have to workaround to use the Launcher.

**Comment by demarey** [comment]
PharoLauncher app is now signed with the same certificate as the Pharo VM.
