### ISSUE TITLE
Launcher's version

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#23]
There must be an indication somewhere of the Launcher's version. That way, users can tell us the version they use when they report a problem.

**Comment by demarey** [comment]
implemented through an 'About' button / command.

-------
Name: PharoLauncher-Core-ChristopheDemarey.156
Author: ChristopheDemarey
Time: 11 January 2018, 11:51:41.150624 am
UUID: 8b3481ab-df1e-0d00-8927-316908755bc2
Ancestors: PharoLauncher-Core-ChristopheDemarey.155

Enhancement #23 : PharoLauncher should display its version. Now available through the 'About' button / command.
-------
Name: PharoLauncher-Spec-ChristopheDemarey.59
Author: ChristopheDemarey
Time: 11 January 2018, 11:51:53.60661 am
UUID: 56393fac-df1e-0d00-8928-f11908755bc2
Ancestors: PharoLauncher-Spec-ChristopheDemarey.58

Enhancement #23 : PharoLauncher should display its version. Now available through the 'About' button / command.
-------
Name: PharoLauncher-Tests-Core-ChristopheDemarey.23
Author: ChristopheDemarey
Time: 11 January 2018, 11:52:10.874337 am
UUID: 49c046ad-df1e-0d00-8929-d56d08755bc2
Ancestors: PharoLauncher-Tests-Core-ChristopheDemarey.22

Enhancement #23 : PharoLauncher should display its version. Now available through the 'About' button / command.
