### ISSUE TITLE
Cannot launch recent Pharo 7 images

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#233]
When trying to run a recent Pharo 70 image from Pharo Launcher, one get:
```
Cannot determine image version: image version file not found!
Try to run this command in a shell to get more information on the problem:
cd "/Users/julien/Documents/Pharo/vms/private/6521/Pharo.app/Contents/MacOS" && "/Users/julien/Documents/Pharo/vms/private/6521/Pharo.app/Contents/MacOS/Pharo" --headless "/Users/julien/Documents/Pharo/images/RTFExperiment-Iceberg/RTFExperiment-Iceberg.image" eval "(Smalltalk imagePath asFileReference parent) / 'pharo.version' 		writeStreamDo: [ :stream | |major minor|			major := SystemVersion current major.			minor := SystemVersion current minor.			(major = 6 and: [ SystemVersion current highestUpdate >= 60509 ])				ifTrue: [ minor := 1 ].			stream 				<< major asString;				<< minor asString ]"
```

When trying to run the given command in UI mode, we got an exception:
<img width="1072" alt="capture d ecran 2018-08-20 a 18 18 50" src="https://user-images.githubusercontent.com/2494203/44516920-a19daa00-a6c6-11e8-8445-71538f7ced2d.png">

**Comment by demarey** [comment]
I opened an issue for the check of the latest VM: #234 .

From Alistair Grant:

> As I understand it, the VM is compatible with
the image format, it is just a bit old and is missing a new primitive
(and since this is within the development cycle we're not trying to
keep backward compatibility, if you're using the latest pharo 7 image
you should be using the latest pharo 7 VM, the rules will change once
pharo 7 is released).

> It would be useful to have a Pharo version embedded in the header of
the image.  That could then be queried and the latest VM for that
version used to start the image.  I think that would cover the
majority of cases.

**Comment by demarey** [comment]
fixed for the current version:

>Name: PharoLauncher-Core-ChristopheDemarey.202
Author: ChristopheDemarey
Time: 23 August 2018, 10:30:27.343614 am
UUID: 702be1ce-7730-0d00-921b-5bd509ca85dd
Ancestors: PharoLauncher-Core-ChristopheDemarey.201
>
> extract version file if present from std images.

Now these changes have to be pushed to git in the development branch

**Comment by olekscode** [comment]
I'm also having this problem on my PharoLauncher (just wanted to report it). 
@demarey was your fix accepted?
Can I load the updated version of Launcher?

**Comment by olekscode** [comment]
Thank you!

**Comment by smashedtoatoms** [comment]
I am getting this problem with the mooc on the latest launcher.  I know nothing about smalltalk, but so far my intro is pretty irritating.  Any ideas on what I can do to get the mooc image to not do this?

**Comment by demarey** [comment]
@smashedtoatoms We understand having an error at the first step is quite frustrating. A lot of Pharo users now use Pharo Launcher and it looks to work fine for most of them. Also, we know that in some situations, it could not work as expected. We are trying to solve problems once they have been identified. Could you tell us more about your problem? I just tried with Pharo Launcher 1.8 to run a fresh mooc image and it worked for me. Could you report the exact error (including trace if any or a screenshot), your operating system and its version, pharo launcher version ? Thanks

**Comment by smashedtoatoms** [comment]
No problem at all.  I eventually got it working.  I have no idea what incantation made it work.  I initially used Pharo Launcher, and it didn't work.  Then I literally downloaded every version from 5 up for windows manually, and had different errors on all of them.  Then I did the same thing for all the version in the Launcher, and for some reason, after downloading and starting every supported version in the launcher, the MOOC image started working.  I have no idea why, but I am unblocked.  I was on the Discord channel last night about it, and here is what I posted there:

Hey all, if anyone has a second, I am trying to run the mooc and on the latest, I am getting the following error on both linux and windows: 

```
pharo.version file was not found for your image, and probably your VMs are not up to date.
Please, contact us at http://pharo.org/community
```

At this point I switched to Linux because the terminal was showing me something that I might be able to do something about.  In the terminal I got: 

```
Error. Could not determine platform's libc path for VM.
Try forcing $PLATFORMLIBDIR in /home/me/Pharo/vms/private/6521/pharo, based on LIBC_SO.
Please report what works to pharo [vm-dev] mail list.
  LIBC_SO=
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=18.04
  DISTRIB_CODENAME=bionic
  DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
  NAME="Ubuntu"
  VERSION="18.04.2 LTS (Bionic Beaver)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 18.04.2 LTS"
  VERSION_ID="18.04"
  VERSION_CODENAME=bionic
  UBUNTU_CODENAME=bionic
  UNAME=Linux me-lap 4.4.0-18356-Microsoft #1-Microsoft Fri Mar 08 16:07:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
  System seems to be 64 bit. You may need to (re)install the 32-bit libraries.
Error. Could not determine platform's libc path for VM.
Try forcing $PLATFORMLIBDIR in /home/me/Pharo/vms/private/6521/pharo, based on LIBC_SO.
Please report what works to pharo [vm-dev] mail list.
  LIBC_SO=
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=18.04
  DISTRIB_CODENAME=bionic
  DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
  NAME="Ubuntu"
  VERSION="18.04.2 LTS (Bionic Beaver)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 18.04.2 LTS"
  VERSION_ID="18.04"
  VERSION_CODENAME=bionic
  UBUNTU_CODENAME=bionic
  UNAME=Linux me-lap 4.4.0-18356-Microsoft #1-Microsoft Fri Mar 08 16:07:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
  System seems to be 64 bit. You may need to (re)install the 32-bit libraries.
```

I tried installing the 32 bit libs, but to no avail.  Bummer

When I manually set LIBC_SO to /lib/i386-linux-gnu/libc.so.6 it fails with: 

```
/home/me/Pharo/vms/private/6521/pharo: 56: exec: /home/me/Pharo/vms/private/6521/lib/pharo/5.0-201901051900/pharo: Exec format error
```

Once that didn't work, I switched back to Windows, installed all the versions from 5 - 8 manually, got nowhere, went back to Pharo Launcher, installed 6-8 with it and tried to open the mooc image with those.  None of those worked either; however, when I then opened up the mooc image, it worked.  Again, I have no idea what changed that mattered.  I guess as I learn more about how it all works together I might be able to figure it out.  In any case, it is working now on Windows.  I haven't gone back and tried to get it working on Ubuntu again.  I wasn't gathering logs as I worked through it, so I apologize for not having better info for you.  I will let you know if I discover what caused it.

**Comment by demarey** [comment]
The Mooc image is based on Pharo 5 which is a 32-bit image. It means that you need to use a 32-bit VM to run it. On linux, it implies you need to follow these instructions https://pharo.org/gnu-linux-installation (_Prepare 64-bit-Linux for 32bit Pharo_ section) to enable 32-bit images support. Probably the error on Linux was related to this.
On Windows, it should work out of the box. We know there are sometimes problem with the process forking library. If you want to give another try, you should remove (or rename) vms folder in the Documents/Pharo folder. Pharo Launcher first tries to determine the image version. If this step does not work, please report it. As a workaround, you could create a file named pharo.version aside the image you want to run. It will be used by PharoLauncher to use the appropriate VM to run the image.


<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo.org/gnu-linux-installation">Pharo - Download - GNU/Linux installation</a></strong></div></blockquote>

**Comment by astares** [comment]
I freshly installed an elder Raspberry pi 3 today with latest Raspbian OS (64 bit). 
I downloaded Pharo and when starting ./pharo-launcher-ui I get

```	not a dynamic executable
	not a dynamic executable
Error. Could not determine platform's libc path for VM. 
Try forcing $PLATFORMLIBDIR in /home/kiwi/pharo-launcher/pharo-vm/pharo, based on LIBC_SO.
Please report what works to pharo [vm-dev] mail list.
  LIBC_SO=
  PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
  NAME="Debian GNU/Linux"
  VERSION_ID="12"
  VERSION="12 (bookworm)"
  VERSION_CODENAME=bookworm
  ID=debian
  UNAME=Linux docbox 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
  System seems to be 64 bit. You may need to (re)install the 32-bit libraries.
```
