### ISSUE TITLE
Remember images sorting

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-project/pharo-launcher#242]
Currently, whenever Launcher is closed and reopened or search field is used, Image list sorting is reset. I use sorting a lot and it would make my life easier if it was preserved (maybe only if settings option is checked?).

**Comment by fuhrmanator** [comment]
I second this feature request. 

I am clicking the "Last modified" sort column 5 times a day or more, because Launcher doesn't remember my choice. 

A typical use case is that I've created a new image, it's put into the list (that was sorted by "Last modified") but is sorted by Name (by default?).

**Comment by demarey** [comment]
done in latest (dev) version
