### ISSUE TITLE
Can't launch multiple launchers on OS X

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#25]
Some users reported they can't launch several launchers on OS X.

**Comment by bestlem** [comment]
That is standard macOS/OSX/NeXT behaviour. The command line call open or running from Finder actually looks for an app and if it is running uses that passing it some information on the command line it only creates a new app if it is needed.
If you call the VM directly from the command line e.g. .../Pharo.app/Contents/MacOS/Pharo then you can have multiple Pharos

**Comment by demarey** [comment]
+1
not a bug
