### ISSUE TITLE
Copy and Rename command should not add a "-01" if the image name already ends with a number

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#274]
I tried to copy an image named "Iceberg-01" and the default named I got was "Iceberg-01-01". I would have expected an "Iceberg-02".

We can check if the name ends with numeric characters and increment it in that case. (Or maybe a character $- followed by numeric characters?)

**Comment by eMBee** [comment]
rename should probably not change the name at all, since i would not call rename to increment the number but change the name for other reasons.

**Comment by demarey** [comment]
@eMBee +1
