### ISSUE TITLE
Refresh launcher on startup

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#280]
Since I customize my launcher I often save my launcher image. Then when I open it, the lists are not updated.

Maybe we could add a startup action to refresh the launcher at startup?

**Comment by eMBee** [comment]
if added, please make this configurable . on a slow connection the launcher is practically unusable while the update happens. so i'd like to be able to turn such a feature off.

**Comment by jecisc** [comment]
I was talking about refreshing the local images list mainly :)

**Comment by demarey** [comment]
Is it still relevant with last version?
