### ISSUE TITLE
Pharo Launcher does not go beyond Pharo 7 #1384 image

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-launcher#281]
Meanwhile Pharo is at image build #1415
http://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2018-November/273628.html

but Launcher on Windows does not show images beyond Pharo 7 #1384

This was also reported by Stephan eggermont on Slack.

**Comment by demarey** [comment]
You can get the latest image from Official Distributions > Pharo 70.
In the Pharo 7.0 (development version) group, latest versions are not shown because the naming changed. PharoLauncher uses the following regexp to list available versions: 
`href="(Pharo-7.0.0-alpha.build.[^"]*.zip)"`
```Smalltalk
matcher := 'href="(Pharo-7.0.0-alpha.build.[^"]*.zip)"' asRegex.
matcher matches: 'href="Pharo7.0.0-rc1.build.1410.sha.5063419.arch.64bit.zip"'. "false"
matcher matches: 'href="Pharo-7.0.0-alpha.build.1379.sha.54328a7.arch.64bit.zip"' "true"
```
I will update this regexp in the upcoming PL version

**Comment by demarey** [comment]
should use `href="(Pharo-?7.0.0-(alpha|rc\d+).build.[^"]*.zip)"`regex

**Comment by astares** [comment]
OK, I changed to:

pharo70
	^ self 
		name: 'Pharo 7.0 (development version)' 
		url: 'http://files.pharo.org/image/70/' asZnUrl
		filterPattern: 'href="(Pharo-?7.0.0-(alpha|rc\d+).build.[^"]*.zip)"'

and run

PhLTemplateGroupRepository resetGroups

and confirm that I now see #1416 build

**Comment by astares** [comment]
Name: PharoLauncher-Core-TorstenBergmann.209
Author: TorstenBergmann
Time: 27 November 2018, 3:09:47.547739 pm
UUID: 5b3c35bd-0738-0d00-93d5-6fca0dc846da
Ancestors: PharoLauncher-Core-ChristopheDemarey.208

Fix for https://github.com/pharo-project/pharo-launcher/issues/281 as discussed on Discord #development channel today
