### ISSUE TITLE
Pharo Launcher picture is missing on web page

### ISSUE THREAD

**Issue by mldavis99** [pharo-project/pharo-launcher#282]
The Picture of the Pharo Launcher is missing on the new web page:  https://github.com/pharo-project/pharo-launcher/    Thank you for the nice update to the home page, it cleans up confusion for many potential new users about how to get started.

![pharo launcher screenshot missing](https://user-images.githubusercontent.com/4325699/49245232-f5f3ac80-f3ce-11e8-92d7-07b41a11269d.jpg)

**Comment by demarey** [comment]
Thanks for reporting this problem.
Also, be aware that the "official" documentation is the Readme of the master branch.
