### ISSUE TITLE
Buttons (Import > Launch an image...) are cut off in Windows 10

### ISSUE THREAD

**Issue by fuhrmanator** [pharo-project/pharo-launcher#286]
Choosing **Import > Launch an image from the file system** gives the following dialog in which the buttons (OK, Cancel) are not visible:

![image](https://user-images.githubusercontent.com/7606540/50150314-e379de00-02bd-11e9-93ca-dbf0fa5aa662.png)

**Comment by demarey** [comment]
The culprint looks to be RealEstateAgent>>#initialFrameFor: world: (used by FileDialogWindow>>#openInWorld)

**Comment by demarey** [comment]
@fuhrmanator Could you tell me if you the bug is still there in this version? http://files.pharo.org/pharo-launcher/1756a5c/

**Comment by fuhrmanator** [comment]
Yes, still there. Here's a screen shot:

![image](https://user-images.githubusercontent.com/7606540/52056722-46b88a80-2563-11e9-91ab-02ebcb00b166.png)

Compared to the last screenshot, it seems the same amount of space vertically. The new one is wider (more horizontal space), but it might just be that I had made the older screen more narrow?
