### ISSUE TITLE
Bug related to maxFileNameLength

### ISSUE THREAD

**Issue by SergeStinckwich** [pharo-project/pharo-launcher#29]
I found a nasty bug on last stable version of PharoLauncher on Mac OS X.
![screen shot 2016-05-03 at 16 55 29](https://cloud.githubusercontent.com/assets/327334/14987978/1367f83c-1152-11e6-9ab3-11734a4fbc76.png)

Apparently this bug occurs only when file name are greater than 255 and because of another bug : 
(MacStore new) maxFileNameLength that returns a String instead of an Integer.

I guess this bug will disappear with PharoLauncher based on Pharo 5.0.

**Comment by DamienCassou** [comment]
Thanks for the report? Is the bug fixed in Pharo 5 already?

**Comment by SergeStinckwich** [comment]
Yes, "(MacStore new) maxFileNameLength" returns an integer

**Comment by demarey** [comment]
Launcher now uses Pharo 6.
I think this issue can be closed as it should already be solved
