### ISSUE TITLE
Add "latest" to indicate dynamic version development versions for Pharo 7.0

### ISSUE THREAD

**Issue by fuhrmanator** [pharo-project/pharo-launcher#290]
Today I learned that "Pharo 7.0 -32bit (development version)" is actually a dynamic version (it can change in the time). I found that misleading because "Moose Suite 6.1 (beta)" seems to be static, etc. 

Anyway, I think the meaning would be much clearer if the word "latest" was included when the version is dynamic.

**Comment by demarey** [comment]
fixed in PL 1.5.1
