### ISSUE TITLE
zipfile from 85bebb7 has no source file

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-launcher#293]
It seems the image generated from 85bebb7 is a pharo7 image but it has no source code.

**Comment by guillep** [comment]
I've tried adding the Pharo sources from the corresponding commit but it does not work. It seems that the launcher is condending changes? That's not good...

**Comment by guillep** [comment]
This makes ffi calls fail...

**Comment by demarey** [comment]
PL does not condense changes. I will take a look at it.

**Comment by demarey** [comment]
OS X app includes 6.1 sources file. It should now be 70 sources file.

**Comment by guillep** [comment]
Yeah, maybe, but even. If I add 70 sources file nothing works.

**Comment by demarey** [comment]
I fixed pb wih sources files. The other problem is that someone disabled PhLStartupManager registration to the startup list ... I reactivated it

**Comment by demarey** [comment]
looks to be fixed
