### ISSUE TITLE
Readme image needs updating

### ISSUE THREAD

**Issue by fuhrmanator** [pharo-project/pharo-launcher#294]
With the release of Pharo 7, shouldn't the screen shot on the Readme here be updated? I can do it with one from my Windows PC, but I'm not sure if it's a great example.

**Comment by demarey** [comment]
good idea. I will release a new version of Pharo Launcher soon. It could be done with the new release

**Comment by demarey** [comment]
Readme will be superseded by https://pharo-project.github.io/pharo-launcher/

<blockquote><img src="img/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo-project.github.io/pharo-launcher/">Home - Pharo Launcher documentation</a></strong></div><div>None</div></blockquote>
