### ISSUE TITLE
Pharo 7 marked as (development version)

### ISSUE THREAD

**Issue by bradrn** [pharo-project/pharo-launcher#295]
I've just downloaded the latest version of Pharo Launcher (1.5.1) so I can try out Pharo 7. However, upon running the Launcher, I noticed that Pharo 7 was still marked as a `(development version)`, with Pharo 6 still at `(stable`). Is this intended, or should Pharo 7 be marked as `(stable)`? A screenshot, with the offending part highlighted:

![image](https://user-images.githubusercontent.com/17613703/51652468-d9957a00-1fe3-11e9-8e68-03117cf5e87e.png)

(sorry about the wobbly writing)

**Comment by stephensmith9** [comment]
+1 on this especially because the Pharo download page says, "For instance you can download "Official distributions" -> "Pharo 7.0 (stable)" which is the latest stable image as of today." 

Or reword the download page to say "Pharo 7.0 - 32bit (stable)" if only the 32bit version is considered stable.

**Comment by demarey** [comment]
thanks for the report.
I just updated the sources list file to mark Pharo 7.0 as the stable version.
If you use the latest version of PharoLauncher, it should automatically update.

**Comment by bradrn** [comment]
Are you sure? For me, it's still reporting Pharo 7.0 as development.

**Comment by demarey** [comment]
You need to have the option "clear templates at startup" activated and relaunch PharoLauncher

**Comment by bradrn** [comment]
I do have that option selected. (Except on mine, it's 'Templates cleared at startup'.) I'm using PharoLauncher 1.5.1, if that's relevant.

**Comment by demarey** [comment]
I did some bug fixes on the development version. Could you give a try at it and tell me if it works better? http://files.pharo.org/pharo-launcher/8eac64c/

**Comment by bradrn** [comment]
Yes; that works - thank you! (And it also seems to give me a new 'VM Manager' - should this also have been in 1.5.1?) Do you have any idea when this will be in a new release? It would be a horrible UX for a new user to download PharoLauncher and see the new version wrongly listed as development...

**Comment by demarey** [comment]
I need to test it a bit more. I think I will release it this week. The VM manager was not included in 1.5.1

**Comment by bradrn** [comment]
Thank you!

(Side question: This may be impractical, but would it be possible to coordinate the Pharo and PharoLauncher release cycles in some way (if it's not done already), since PharoLauncher is the easiest way to run Pharo?)

**Comment by stephensmith9** [comment]
> 
> 
> I did some bug fixes on the development version. Could you give a try at it and tell me if it works better? http://files.pharo.org/pharo-launcher/8eac64c/

When I downloaded the .msi file from here and tried to install it, it says I already have a newer version of PharoLauncher installed. I'm using 1.5.1. Is the Windows version patched to show 'stable' for 7.0 images?
