### ISSUE TITLE
HTTP Proxy authentication missing from settings

### ISSUE THREAD

**Issue by Gotchas99** [pharo-project/pharo-launcher#30]
In the normal settings you can setup a HTTP proxy and also authentication for this proxy. In the Launcher settings you can ony setup the proxy, but not the authentication.

This means the launcher can't be (easily) used if you're located behing a proxy that requires authentication.

I suggest we include (copy-paste?) the authentication settings into the launcher.

![image](https://cloud.githubusercontent.com/assets/4977241/16453148/1d03e1d0-3e0c-11e6-8796-07cb000ceceb.png)

**Comment by demarey** [comment]
already done
