### ISSUE TITLE
Missing Publisher or certificate on Windows Installer

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-launcher#300]
When downloading and installing launcher on Windows the SmartScreen filter laments.
Dont know if it is possible to fix the publisher or if a code signing certificate (from Verizon or other, applied with signtool.exe) is required to fix that:

![image](https://user-images.githubusercontent.com/5980033/51829509-fb497680-22ed-11e9-94b9-0e71d5f45f7a.png)

**Comment by demarey** [comment]
Sadly, we are now forced to sign executables manually for Windows. In fact, we have to ask someone to sign for us. We will upload a signed version ASAP

**Comment by astares** [comment]
Why manually? Can you elaborate?

**Comment by demarey** [comment]
Because our new certificate is shipped in a USB dongle and we do not have access directly to the file to use it to sign automatically :(

**Comment by astares** [comment]
USB Dongles in todays world of virtualizations and cloud computing - Aaargh

**Comment by demarey** [comment]
fixed in 1.6
