### ISSUE TITLE
Create template broken

### ISSUE THREAD

**Issue by bencoman** [pharo-project/pharo-launcher#301]
Right-clicked on an image, the Create Template and got a debugger "Instance of FileReference did not understand #utf8Encoded"

Looking back along the stack is...
```
PhLTemplateGroupRepository>>createZipArchiveFrom: anImage named: aString
	ZipArchive new
		addFile: anImage imageFile as: aString , '.image';
		addFile: anImage changesFile as: aString , '.changes';
		writeToFileNamed: PhLDownloadedTemplateGroup default baseDirectory / aString , 'zip'
```
where... ```anImage imageFile``` is a FileReference 
but a String is expected... ```ZipArchive>>addFile: aFileName as: anotherFileName```

Simple fix by generous use of #fullName...
```
PhLTemplateGroupRepository>>createZipArchiveFrom: anImage named: aString
	ZipArchive new
		addFile: anImage imageFile fullName as: aString , '.image';
		addFile: anImage changesFile fullName as: aString , '.changes';
		writeToFileNamed: (PhLDownloadedTemplateGroup default baseDirectory / aString , 'zip') fullName
```

P.S. I'm a bit confused where to contribute.  PharoLauncher seems to have been migrated to github (as I would expect), but the Smalltalkhub code looks newer.

**Comment by demarey** [comment]
Hi Ben,

Thanks for the report (and the fix).
To contribute, you can issue a PR on this repository.
All code that was on Smalltalkhub has been integrated into this repo.
