### ISSUE TITLE
Current Images filter edit box filters in real-time so help text is not applicable 

### ISSUE THREAD

**Issue by stephensmith9** [pharo-project/pharo-launcher#303]
Just above the Current Images list is a filter control. It currently says, "Hit return to accept" but at least in v1.6 it filters out the list dynamically, as you type (a nice feature), so the help text is not applicable (maybe it was at one time?). 

I would like to suggest that it would be beneficial to change the text to say, "Filter..." to match what the filter box in the Calypso system browser says at the bottom of the package pane, for consistency across the platform. This also clues in the user as to what the edit box is for (though most should figure it out).

**Comment by demarey** [comment]
right, thanks for the report
