### ISSUE TITLE
No Pharo 8 template in version 1.6

### ISSUE THREAD

**Issue by dupriezt** [pharo-project/pharo-launcher#308]
Linux Ubuntu 18.04.1 LTS

I downloaded the 1.6 version of the Pharo Launcher to get templates for Pharo 8 images.
The first time I ran it, I had these templates.
The second time and onward, it was back to only having templates up to "Pharo 7 (development version)".

**Comment by dupriezt** [comment]
Going to the settings, checking "Clear templates at startup" an clicking "store settings" solves the issue. All the Pharo Launcher I launched afterward had the pharo 8 template.

If I remove this option however, the new Pharo Launcher I open are back to only having templates up to "Pharo 7 (development version)".

**Comment by demarey** [comment]
could you tell me if http://files.pharo.org/pharo-launcher/2fec3b3/ fixes your problem?

**Comment by demarey** [comment]
fix is done in c0c6e2ba187235fa6a4436a9633dfc9c1285279e

**Comment by dupriezt** [comment]
It works for me. Nice :+1: 
I have the pharo 8 templates without having to have the "Clear templates at startup" setting on.
