### ISSUE TITLE
pharo not executable on linux

### ISSUE THREAD

**Issue by HeSe** [pharo-project/pharo-launcher#31]
Hi!
I have linux mint here and I debugged the reason why my downloaded image won't start.

First, after the download of the needed vm the sources file is not situated in
/home/myuser/Pharo/vms/60/lib/pharo/5.0-201705310241
and a PharoDebug.log ist created stating this error,

Second, the /home/myuser/Pharo/vms/60/lib/pharo/5.0-201705310241/pharo is not executable.
Images are not started but no error is presented or logged.

Reason
PhLVirtualMachineManager ensureIsExecutable: is only doing a "chmod u+x" on 
/home/myuser/Pharo/vms/60/pharo
and not
/home/myuser/Pharo/vms/60/lib/pharo/5.0-201705310241/pharo

This is an example for pharo6.0 images but the error applies for all versions.

Could somebody please have a look into this?

Thank you!
Sebastian

**Comment by demarey** [comment]
Hi Sebastian,

I replied too quickly on the ML.
Thanks for this information. I will fix that ASAP. I tested on my laptop ant it worked fine. I will try to reproduce your problem.

**Comment by demarey** [comment]
There is a problem on the detection of the pharo executable path on Linux. I'm fixing it.

**Comment by demarey** [comment]
On linux, I now check the 4 first bytes of the file to detect the ELF magic number.
There is still a problem with the sources file location. I will also fix it.

**Comment by demarey** [comment]
Could you test if the latest version works for you?

**Comment by HeSe** [comment]
Based on : linux 0.2.13-1 with 
PharoLauncher-user-bleedingEdge-2017.08.02.zip 
<https://ci.inria.fr/pharo/view/Launcher/job/Launcher/PHARO=61,VERSION=bleedingEdge,VM=vm,label=linux/lastSuccessfulBuild/artifact/PharoLauncher-user-bleedingEdge-2017.08.02.zip>
I get the old behavior

Same thing when I load the latest core package.

Sebastian

**Comment by HeSe** [comment]
Hi!

I was wrong. It works for Pharo 6.0 now, but it still fails for Pharo 5.0.

Sebastian

**Comment by HeSe** [comment]
Hi!

I gave the launcher another try with the version from this morning.

The 5.0 image does still not launch.

I debugged the code and there seems to be a problem with the OSProcess.

The OSProcess is supposed to run this command:
"/home/mysuser/Pharo/vms/50/pharo" 
"/home/myuser/Pharo/images/latest50/latest50.image"

this works in the transcript!

But OSProcess command:  -c '"/home/mysuser/Pharo/vms/50/pharo" 
"/home/myuser/Pharo/images/latest50/latest50.image"'

Does not start the image...

Sebastian

**Comment by demarey** [comment]
Yes, I tried to debug the problem yesterday but did not succeed.
Indeed, if you run the command that OsProcess is supposed to run in a terminal, it works.
What do you meand by running in transcript?
With OsProcess, the VM cannot find the file vm-display-X11. I have a workaround: doing a `cd` in the vm directory before running the command. But, then, I have an error in the image with the loading of FreeTypeFonts: FreeType2 primitive failed [error-1][can't get error string].

**Comment by HeSe** [comment]
Hi!

I am sorry, I ment "Terminal" not transcript...

I am not familiar with the Pharo Core system and do not know where to 
check if they might have an issue open on OsProcess on linux...

Do you know?

**Comment by demarey** [comment]
Hi,

Sorry for the delay, but I finally managed to get the problem. When launching an image from the launcher, a process is forked with OSProcess. This new process inherits the environment from the old one. It looks like the VM is setting an environment variable SQUEAK_PLUGINS that is used by the VM is set. So, when running a new image / vm from the launcher VM, we got a wrong path for plugins causing the FT2 error. 
Resetting the SQUEAK_PLUGINS env var + getting in the VM directory before running the VM solved the issue.
Could you test the latest version and tell me if it is ok?
