### ISSUE TITLE
upgrade not possible on Windows: A more recent version of PharoLauncher is already installed on this computer

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#310]
From Petr Fischer:

I thought I'd try PharoLauncher again after some time and I really have a bad luck with this product.
I have a PharoLauncher version 1.5.1 installed. If I run new 1.6 installer, this error occurs:
"A more recent version of PharoLauncher is already installed on this computer"
https://app.box.com/s/rbn1n12zvx5rvy4zb1s0fujhkbzwvone

"More recent?..." Really?

I uninstalled old version manually of course, but... PharoLauncher can't update itself?

Platform: Windows 10 Pro [1809]

**Comment by petr-fischer** [comment]
Note: with some probability, this issue occurs in transition from version 1.5.1 (or prior)  to 1.6. When I have 1.6 installed and run 1.6 installer again - no issues with version detection - the installer will offer me the right options: Repair installation ,Modify installation, Remove.

**Comment by demarey** [comment]
I think I found the problem. The version of Pharo Launcher 1.6 package is `0.0.0`(used for bleeding-edge versions).
![pl16](https://user-images.githubusercontent.com/2494203/52637778-8a4eb500-2ed0-11e9-84a4-ca7bb508ef17.PNG)

**Comment by demarey** [comment]
the problem was introduced in c6076ac143410fbc21fbec7ee11b54a177b46813

**Comment by demarey** [comment]
fixed in 1.7.2 e6b5f61d7fba352f6e4ba09f3cc736d33d99c639

**Comment by astares** [comment]
Had the same issue when upgrading. Gives a wrong impression to new users.

Glad that it is fixed now. Thanks for caring!

**Comment by JanBliznicenko** [comment]
I installed the unsigned .msi from https://files.pharo.org/pharo-launcher/1.7.2 but the old (0.0.0) version remained in list of installed applications too instead of being replaced. It never happened with previous versions (prior to 1.6).
