### ISSUE TITLE
A more recent version of PharoLauncher is already installed on this computer

### ISSUE THREAD

**Issue by rillig** [pharo-project/pharo-launcher#312]
I visited https://pharo.org/download and clicked on the Windows link. I downloaded pharo-launcher-1.6.msi.

When I started the installer, it said:

> ![image](https://user-images.githubusercontent.com/3233724/52914156-34f61780-32c5-11e9-9bba-a6288abcd366.png)

I doubt that I have installed a more recent version than 1.6. Maybe the same version, but definitely not a newer one.

> ![image](https://user-images.githubusercontent.com/3233724/52914164-6373f280-32c5-11e9-8823-59b35d0655ff.png)

The error message should be made more realistic.

After deinstalling version 1.4.6 and installing version 1.6, the app installation settings say:

> ![image](https://user-images.githubusercontent.com/3233724/52914238-4f7cc080-32c6-11e9-9639-acf40f69051b.png)

**Comment by JanBliznicenko** [comment]
Fix has already been made (duplicite to closed issue #310 ), but the fixed version has not yet been published. You may try downloading unsigned .msi from https://files.pharo.org/pharo-launcher/1.7.2/ (works for me with UAC turned off, but I had to remove old version manually)
