### ISSUE TITLE
Misspellings: persistant, let's

### ISSUE THREAD

**Issue by rillig** [pharo-project/pharo-launcher#313]
The PharoLauncher contains the misspelled word "[persistant](https://en.wiktionary.org/wiki/persistant)" in several places. It should be "persistent".

The one-liner at https://github.com/pharo-project/pharo-launcher says "Let's you manage". It should be "Lets you manage" since it does not mean "let us".

The tooltip for the "Hard reset persistant state" contains the word "clsoed". It should be "closed".

The tooltip for the "VMs Directory" contains "to launcher your". It should be "to launch your".

**Comment by demarey** [comment]
> The PharoLauncher contains the misspelled word "[persistant](https://en.wiktionary.org/wiki/persistant)" in several places. It should be "persistent".

fixed

> The one-liner at https://github.com/pharo-project/pharo-launcher says "Let's you manage". It should be "Lets you manage" since it does not mean "let us".

fixed

> The tooltip for the "Hard reset persistant state" contains the word "clsoed". It should be "closed".

fixed

> The tooltip for the "VMs Directory" contains "to launcher your". It should be "to launch your".

fixed too.

Thank you for taking time to report this.
