### ISSUE TITLE
Cannot find VMs on Windows

### ISSUE THREAD

**Issue by webwarrior-ws** [pharo-project/pharo-launcher#32]
When trying to launch any image, exception is raised (key '60' not found in Dictionary).

Looks like the problem is in `#vmExecutableName` method: on Windows, it should return 'Pharo.exe'.

**Comment by webwarrior-ws** [comment]
After fixing `#vmExecutableName`, works as expected.

**Comment by demarey** [comment]
Which version do you use? It should already be fixed in the latest version.

**Comment by webwarrior-ws** [comment]
@demarey 
0.2.13 - latest stable build according to Jenkins.

**Comment by demarey** [comment]
ok. Could you download and try again 0.2.13? I fixed it this morning.

**Comment by webwarrior-ws** [comment]
Just tried it; fresh install. Didn't help.

**Comment by demarey** [comment]
sorry, I forgot to merge the fix. It should now work.
Also, I do not know why, sometimes, OSProcess hangs on waiting a command that is already finished. Let me know if you also have this behavior.

**Comment by webwarrior-ws** [comment]
Yes, now it works.
I haven't encountered any OSProcess problems.
