### ISSUE TITLE
Edit image description doesn't update when editing existing description

### ISSUE THREAD

**Issue by stephensmith9** [pharo-project/pharo-launcher#326]
Using v1.7.2 on Windows 10 (64bit).

If I try to edit the image description of one of my images via the right-click->Edit image description popup menu, the changes do not save correctly. 

For example, changing an existing description of "My image description is too long" to "My image description" by backspacing over the last three words, still shows the old (longer) description.

When overwriting the existing text, as long as the overwritten text is longer than the original text, the original text gets successfully overwritten. However, if I make my overwrite shorter than the original, then the remaining part of the original text still shows.

For example,
Orig desc: "My image description."
Edited desc: "My image description is longer now." - successful
Edited desc: "My image description is shorter." - produces "My image description is shorter.ow."

**Comment by demarey** [comment]
Thanks for the report.
I discovered the same kind of problem in another project I work on. I assumed that writing data by using a write stream on an existing file reference would override the whole file but it is not the case. If you write less data than the previous file content, then there is a leftover of the previous content.
