### ISSUE TITLE
Support for urls and jenkins servers that require authentication

### ISSUE THREAD

**Issue by jbrichau** [pharo-project/pharo-launcher#331]
Pharolauncher requires the `sources.list` on a public url and can only work with public jenkins servers. Support for authentication on both of these items will allow to also use the pharolauncher with private projects. 

Suggestion:
- when (basic) authentication is required on the url for the `sources.list`, the username and password can be entered interactively and stored in the image of the pharolauncher
- when the jenkins server requires authentication, we ask the API key interactively and store it in the pharolauncher image too.

If you agree this should be possible, I will work a bit on this and propose a PR

**Comment by jecisc** [comment]
If you work on that, I already started some work in a project on my smalltalkhub. My user is CyrilFerlicot and the project should be something like SynLauncher or SynectiqueLauncher. (Cannot check now)

I had private project working with a Jenkins token but never got the time to clean my implementation et push it in the launcher :( And it’s probably broken with latest PL updates.

**Comment by jbrichau** [comment]
I already have it working actually ;)
Nothing too difficult: just asking and storing credentials if a url requires it.

Will probably submit a PR this week.

**Comment by demarey** [comment]
Thanks for pushing that Johan.
It is not yet done but we try to have the Pharo Launcher image "non-persistent", i.e. do not allow (at leat do not use) write to the image.
Would it be possible to store credentials in the sources list file? If not, keep it as it is now.
