### ISSUE TITLE
After creating image, it should be selected for play on the right side

### ISSUE THREAD

**Issue by fuhrmanator** [pharo-project/pharo-launcher#339]
I'm on WSL (Ubuntu) Pharo, and I have a lot of images. When I create a new one, it's somewhere on the list on the right, but it's always a challenge to find it with a long list.

It would be very useful to me (and I think others) to have PL select (or highlight somehow?) the newly created image after it's put in the list on the right side. I think it should also be easy to implement.

**Comment by demarey** [comment]
implemented in latest (dev) launcher
