### ISSUE TITLE
Pharo Launcher downloads and settings are down

### ISSUE THREAD

**Issue by chicoary** [pharo-project/pharo-launcher#341]
What is going on?

![Screen Shot 2019-06-25 at 12 30 16](https://user-images.githubusercontent.com/7659991/60111821-0b526e80-9745-11e9-9005-0604062f0bea.png)

**Comment by PharoProject** [comment]
http://files.pharo.org <http://files.pharo.org/> has problems. This server is hosted at OVH.

See for incident report progress: 
https://www.ovh.com/fr/support/status/ <https://www.ovh.com/fr/support/status/>

I added this as https://github.com/pharo-project/pharo/issues/3626 <https://github.com/pharo-project/pharo/issues/3626>

**Comment by MarcusDenker** [comment]
should be working again

**Comment by chicoary** [comment]
Looks like it's working again.
