### ISSUE TITLE
https://files.pharo.org/pharo-launcher/linux64 downloads 1.8 version and not 1.9.x

### ISSUE THREAD

**Issue by fuhrmanator** [pharo-project/pharo-launcher#348]
I wanted to update Pharo Launcher under Linux today so I could see the latest Moose 8.0 under **Official distributions**. On the page http://pharo.org/download, I clicked the **GNU/Linux** button, which points to https://files.pharo.org/pharo-launcher/linux64 and downloads a PharoLauncher-linux-1.8-x64.zip file, which is not the latest version.

**Comment by brickviking** [comment]
The same also appears to be true for all other operating systems... I checked the other three downloads, they all pointed to the 1.8 version.

**Comment by demarey** [comment]
There was a problem with 1.9.2 build that is now fixed.
1.9.2 is now promoted as the default stable version.
