### ISSUE TITLE
Error first start

### ISSUE THREAD

**Issue by SchweinchenFuntik** [pharo-project/pharo-launcher#373]
Using `PharoLauncher-linux-1.9.2-x64`. library installed, version 0.28.4. 

![image](https://user-images.githubusercontent.com/22637705/72741994-7d8f1280-3bb1-11ea-9955-e1b0542863ef.png)

log - [PharoDebug.log](https://github.com/pharo-project/pharo-launcher/files/4087036/PharoDebug.log)

![image](https://user-images.githubusercontent.com/22637705/72742298-1756bf80-3bb2-11ea-9159-3b5b35eef2fb.png)

When starting the image: `"<cdecl: long 'git_libgit2_init' () module: '/home/funtik/Pharo/vms/80-x64/lib/pharo/5.0-201902062351/libgit2.so'>"`

As far as I understand, your version of the library does not support my bastard. About six months ago, everything worked

**Comment by Trapez** [comment]
Same when launching Pharo 8.

**Comment by SchweinchenFuntik** [comment]
as I understand it, the old version (5th) is taken as the basis

![image](https://user-images.githubusercontent.com/22637705/72791492-17050580-3c40-11ea-9c56-632df8a28535.png)

**Comment by SchweinchenFuntik** [comment]
update system - now working

**Comment by SchweinchenFuntik** [comment]
when this library did not change version
