### ISSUE TITLE
pb when editing default config

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#384]
when trying to save the configuration through `#saveSelectedConfiguration`, `selectedConfiguration` is nil, even if Default is selected.

**Comment by jecisc** [comment]
I am wondering... Should the default config be editable?

What is we mess it up?

**Comment by demarey** [comment]
I think we can let the default config editable.
If you mess it, you can always remove it. It will be re-created with default values.
Also, it is the config that will be selected as default. It is better to have the possibility to change it.
