### ISSUE TITLE
Saving a configuration seems to do nothing

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#387]
I created a new configuration and when I click on "Save", nothing happens.

**Comment by jecisc** [comment]
Talking to Christophe, it's just missing feedback.

What I think should be done:
- Add feedback
- Add a second button. One would save the configuration. The other would save the configuration, select it and close the dialog.

**Comment by demarey** [comment]
done.
See 2121321f9491db62c701b425ba7539826fb3419d
