### ISSUE TITLE
ConnectionClosed: Cannot read data

### ISSUE THREAD

**Issue by vitormcruz** [pharo-project/pharo-launcher#40]
I am on Windows behind a proxy and I tried it with pharo 6.1 stable and 7 development. After I create an image, when I try to run it a http fetching process steps in, but it always stop with the following message and stacktrace:

**ConnectionClosed: Cannot read data**

> ZdcSocketStream(ZdcSimpleSocketStream)>>fillBytes:startingAt:count:
> ZdcSocketStream>>readInto:startingAt:count:
> ZnLimitedReadStream>>readInto:startingAt:count:
> ZnLimitedReadStream>>next:into:startingAt:
> ZnLimitedReadStream>>next:into:
> ZnUtils class>>streamFrom:to:size:
> ZnStreamingEntity>>writeOn:
> [ self entity writeOn: fileStream ] in [ :fileStream | 
> fileStream binary.
> self withProgressDo: [ self entity writeOn: fileStream ] ] in ZnClient>>downloadEntityTo: in Block: [ self entity writeOn: fileStream ]
> [ ^ block value ] in ZnClient>>withProgressDo: in Block: [ ^ block value ]
> [ activeProcess psValueAt: index put: anObject.
> aBlock value ] in ZnSignalProgress(DynamicVariable)>>value:during: in Block: [ activeProcess psValueAt: index put: anObject….
> BlockClosure>>ensure:
> ZnSignalProgress(DynamicVariable)>>value:during:
> ZnSignalProgress class(DynamicVariable class)>>value:during:
> ZnClient>>withProgressDo:
> [ :fileStream | 
> fileStream binary.
> self withProgressDo: [ self entity writeOn: fileStream ] ] in ZnClient>>downloadEntityTo: in Block: [ :fileStream | …
> [ aBlock value: stream ] in FileReference(AbstractFileReference)>>writeStreamDo: in Block: [ aBlock value: stream ]
> BlockClosure>>ensure:
> FileReference(AbstractFileReference)>>writeStreamDo:
> [ self writeStreamDo: doBlock ] in FileReference(AbstractFileReference)>>writeStreamDo:ifPresent: in Block: [ self writeStreamDo: doBlock ]
> False>>ifTrue:ifFalse:
> FileReference(AbstractFileReference)>>writeStreamDo:ifPresent:
> ZnFileSystemUtils class>>newFileNamed:do:
> ZnClient>>downloadEntityTo:
> ZnClient>>downloadTo:
> [ (self newHTTPClientForUrl: url) downloadTo: destinationFile ] in PhLDownloadManager>>download:toFile: in Block: [ (self newHTTPClientForUrl: url) downloadTo: dest…etc…
> BlockClosure>>on:do:
> [ :bar | 
> workBlock
>  on: HTTPProgress
>  do: [ :progress | 
>  bar label: progress printString.
>  progress isEmpty
>  ifFalse: [ bar current: progress percentage ].
>  progress resume ] ] in PhLDownloadManager>>displayProgressDuring: in Block: [ :bar | …
> [ :bar | aBlock value: bar ] in MorphicUIManager>>informUserDuring: in Block: [ :bar | aBlock value: bar ]
> BlockClosure>>cull:
> [ ^ block cull: self ] in [ self prepareForRunning.
> CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ ^ block cull: self ]

**Comment by vitormcruz** [comment]
Something related to proxy, maybe? It worked at my home using a windows 10.

**Comment by demarey** [comment]
Thanks for the report.
Could you tell me if you downloaded some Pharo image successfully? If yes, it is strange  because the same code is used to download images, sources file, and virtual machines: `PhLDownloadManager>>#download:toFile:`
Maybe you can give me parameters values of `#download:toFile:` to help reproducing the problem?

**Comment by vitormcruz** [comment]
Yes, pharo image download was successfull.

`PhLDownloadManager>>#download:toFile:`

url: http://files.pharo.org/get-files/61/pharo-win-stable.zip
destinationFile: C:\Users\<user>\Documents\Pharo\vms\61-x86.zip

It must have something to do with proxy.

**Comment by vitormcruz** [comment]
Man, I don’t understand, I deleted the file 61-x86.zip, tried again and know it worked, I have no idea what happened before.

**Comment by vitormcruz** [comment]
With Pharo 7 I got the same error, tied to delete the file, but the error persists.

**Comment by svenvc** [comment]
Debugging problems with proxies that only exist at a specific location is close to impossible.

Does a simple HTML GET work inside your image behind a proxy ?

'http://zn.stfx.eu/zn/small.html' asZnUrl retrieveContents.

**Comment by vitormcruz** [comment]
Data from proxy:

data_send: read -1 of 2048 / 2635109 of 7009008 (errno = Connection reset by pee
r)
data_send: fds 4:5 warning -1 (connection closed)
Could not send whole body
forward_request: palive=0, authok=1, ntlm=0, closed=1

Thread finished.

Connection is being reset-closed. I am not sure if a proxy or server problem.

**Comment by vitormcruz** [comment]
@svenvc Yes, it works, I got:

<pre><html>
<head><title>Small</title></head>
<body><h1>Small</h1><p>This is a small HTML document</p></body>
</html></pre>

that's the strange part. I am tring to figure if the problem is with the proxy, but most things works, so it is strange.

**Comment by vitormcruz** [comment]
Humm, I tried to fecth http://files.pharo.org/get-files/70/pharo-win-stable.zip from the browser and it failed, maybe it is a problem with the servers? I had some problems downloading files from most pharo websites in the last days (Pharo download, zeroconf, pharo launcher etc. Download is really slow,  sometimes it works sometimes don't. I have tried in windows behind a proxy and don't.

Also, 'http://files.pharo.org/get-files/70/pharo-win-stable.zip' asZnUrl retrieveContents. didn't work, connection closed.

**Comment by svenvc** [comment]
It might be related to size. Does

'http://get.pharo.org/70' asZnUrl retrieveContents.

work ?

But is things also fail outside Pharo, then there is some external problem.

**Comment by vitormcruz** [comment]
Yes:

#!/usr/bin/env bash
#<html><head>
<title>Pharo Zeroconf Script</title>
<style>
	BODY, TABLE { 
		font-family: Arial;
		line-height: 1.5em;
	}
	BODY { 
		background-color: white;
		margin-top: -1.5em;
	}
	TD { 
		vertical-align: top;
		padding: 0 1ex 0 0;
	}
	PRE, CODE { 
		background-color: #EEE;
		padding: 0.5ex 0.8ex;
		border-radius: 0.5ex;
	}
	A { 
		color: black;
	}
	</style>
<body>
<h1>Pharo Zeroconf Script</h1>
<p>This script downloads the latest Pharo 70 Image.</p>
<h2>Usage</h2>
<code>curl <a href="http://get.pharo.org/70">get.pharo.org/70</a> | bash </code>
<br/>
or if <code>curl</code> is not available: </br>
<code>wget -O- <a href="http://get.pharo.org/70">get.pharo.org/70</a> | bash </code>

<h2>Artifacts</h2>
<table><tr><td>Pharo.changes</td><td>A changes file for the Pharo Image</td></tr>
<tr><td>Pharo.image</td><td>A Pharo image, to be opened with the Pharo VM</td></tr></table>

<!--
HTML_HELP
# --!></body></html>

**Comment by vitormcruz** [comment]
If it is an external problem, where should I report it?

**Comment by svenvc** [comment]
If it works for you at home (no proxy), works at work for small files (with proxy) and fails at work for large files (with proxy), then is could be a networking problem at work. Maybe you can ask a sys admin for help.

**Comment by vitormcruz** [comment]
No, it fails at home without proxy as well. It seems intermitent.

**Comment by svenvc** [comment]
There seems to be an issue with files.pharo.org (of which get.pharo.org is part), sys admins of those machine have looked at it, and declared that they could not see a problem and closed the support ticket (duh).

But you know how this goes, if they problem is hard to replicate. See the Pharo ML.

**Comment by vitormcruz** [comment]
Thanks, anyway, don't seems to be a problem with launcher, I gess the issue can be closed.
