### ISSUE TITLE
#selectedMorphList was sent to nil

### ISSUE THREAD

**Issue by vitormcruz** [pharo-project/pharo-launcher#41]
In Windows, when I ty to select the "latest" item from Pahro 6.0 list I got this error:

**#selectedMorphList was sent to nil**
UndefinedObject(Object)>>doesNotUnderstand: #selectedMorphList
MorphTreeNodeMorph>>selected:
MorphTreeNodeMorph>>update:
[ :aDependent | aDependent update: aParameter ] in SpecTreeNodeModel(Model)>>changed: in Block: [ :aDependent | aDependent update: aParameter ]
DependentsArray>>do:
SpecTreeNodeModel(Model)>>changed:
[ :w | 
w changed: #select.
w model selectionChanged.
w dependents do: [ :e | e changed ] ] in MorphicTreeNodeAdapter>>select in Block: [ :w | ...
BlockClosure>>cull:
SpecTreeNodeModel(ProtoObject)>>ifNotNil:
MorphicTreeNodeAdapter(AbstractAdapter)>>widgetDo:
MorphicTreeNodeAdapter>>select
MorphicTreeNodeAdapter>>selected:
MorphicTreeNodeAdapter(AbstractAdapter)>>update:with:
[ :aDependent | aDependent update: anAspect with: anObject ] in TreeNodeModel(Model)>>changed:with: in Block: [ :aDependent | aDependent update: anAspect with: ...etc...
DependentsArray>>do:
TreeNodeModel(Model)>>changed:with:
[ :aBoolean | self changed: #selected: with: {aBoolean} ] in TreeNodeModel>>initialize in Block: [ :aBoolean | self changed: #selected: with: {aBoo...etc...
BlockClosure>>cull:
BlockClosure>>cull:cull:
BlockClosure>>cull:cull:cull:
BlockClosure>>cull:cull:cull:cull:
[ :announcement :ann | 
aBlock
	cull: announcement newValue
	cull: announcement oldValue
	cull: announcement
	cull: ann ] in NewValueHolder>>whenChangedDo: in Block: [ :announcement :ann | ...
BlockClosure>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver: in Block: [ action cull: anAnnouncement cull: announcer ]
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt: in Block: [ "Ensure delivery to remaining announcements" sub...etc...
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:

**Comment by demarey** [comment]
It works for me but I can get the same error from time to time when clicking in the tree very quickly on different items. I fear it is a problem of the tree widget implementation. Maybe we should update it to use the new FastTable/FastTree component.

**Comment by vitormcruz** [comment]
Yes, seems a intermitent.

**Comment by bpieber** [comment]
I think I can reproduce it on macOS Sierra 10.12.6:
1. Click Refresh template list
2. Expand Pharo 6.0
3. Collapse Pharo 6.0
4. Expand Pharo 6.0
5. Select Pharo 6.0 > latest => error happens

**Comment by akevalion** [comment]
Hi another way to reproduce this issue in Mac
OS version Mac OS - 10.13.3
PharoLauncher version 1.1.1
http://files.pharo.org/pharo-launcher/tmp-1.1.1/
load P.L version 1.1.1

1. Open the P.L
2. In templates area, try to load some templates
3. Then select one template, collapse one template, expand and select
4. A debugger error window appears with the message  #selectMorphList was sent to nil
5. Current result: Sometimes when you try to load and select some templates an error window appear

**Comment by VincentBlondeau** [comment]
Same under Windows
