### ISSUE TITLE
VMManager: Update on empty VM list raises SubscriptOutOfBounds exception

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-launcher#426]
- open VM manager
- remove all VMs
- click on "Update" button
=> SubscriptOutOfBounds exception

![image](https://user-images.githubusercontent.com/5980033/75901816-63e31b00-5e3f-11ea-937e-d8e567f714dd.png)

**Comment by demarey** [comment]
fixed in dev version.
Thanks for the report
