### ISSUE TITLE
VM Update to handle "url not found" error

### ISSUE THREAD

**Issue by bencoman** [pharo-project/pharo-launcher#431]
I had skipped a few notices that an update was available since I was in the middle of some development and wanted things static for a while.  Now having time to update the VMs, I opened the VM panel and clicked "Update" 
![image](https://user-images.githubusercontent.com/1713447/76672061-2c116b80-65d5-11ea-85e8-e87fd58cff23.png)

and got an error straight away...
![image](https://user-images.githubusercontent.com/1713447/76671847-9cb78880-65d3-11ea-8ea7-fe116bba6a3f.png)

The "errors" variable from context on second line shows...
```
"a CollectionValueHolder[ an OrderedCollection(
'https://files.pharo.org/get-files/old/pharo-win-stab...et-files/old/pharo-win-stable.zip'
'https://files.pharo.org/get-files/old/pharo-win-stable.zip') ]"
```

Trying the url "https://files.pharo.org/get-files/old/pharo-win-stable.zip" directly in a browse shows file doesn't exist, and indeed neither does "https://files.pharo.org/get-files/old/"

So myself I'm easily able to work around this by ignoring the first entry, but contributing factors to a poor UI experience for newcomers.
a) Unhandled "missing file" exception - its reasonably common for files to be missing so this is not an error in the code, so should be handled mroe friendly.
b) "old"  is on the first line, so users don't get a chance to see to see a success before the failure.

So I will try attending to a),  but btw also what should be done about b) ?

**Comment by demarey** [comment]
https://github.com/pharo-project/pharo-launcher/commit/0036b22f022bbf3b49a2804effad21d8c017a361 is also related.

The issue is solved but with a less nice ui. We could try to improve it by using a SpLinkPresenter in the PhLRetryPresenter.
