### ISSUE TITLE
Pull request images

### ISSUE THREAD

**Issue by tesonep** [pharo-project/pharo-launcher#433]
It will be nice to have a category in the tree to get the images produced during the testing of the Pharo Pull-Request in the CI. 
Maybe this tree part can be hidden by a setting to not make noise to the new players.

**Comment by demarey** [comment]
In the dev version of Pharo Launcher, you can add your own sources to Launcher.
Define a file mysources.list in the <Documents>/Pharo directory with this content:
```ston
[
    PhLTemplateSource {
        #type : #JenkinsServer,
        #name : 'Pharo',
        #url : 'https://ci.inria.fr/pharo-ci-jenkins2/'
    }
]
```

With the help of the commit referenced above, you should get what you need
