### ISSUE TITLE
Adding a new image clears the sorting of the list

### ISSUE THREAD

**Issue by tesonep** [pharo-project/pharo-launcher#434]
Steps to reproduce:

1. Sort the list clicking on the header bar.
2. Add a new image. 

Result:
The sort of the list is lost.

**Comment by jecisc** [comment]
+1 and I have to add that the new image is not selected.

**Comment by jecisc** [comment]
Also:
- I sorted
- I created a new image
- I sorted again
- I launched an image

And the launched image is not the one I selected. I guess there is a problem with the selection when the table is refreshed while it was sorted.
