### ISSUE TITLE
source list gets overriden on update :(

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-launcher#436]
I updated locally my source.list to add Pharo9 history (I wasnted to do a bisect to find the cause of a bug).

Today the launcher asked me to update, I said "YES" and I lost my edition of the sources :(.

Maybe what I did is not standard, but we should get a way to "update the sources", adding or removing entries without getting that overwritten :).

I was on launcher 1.9.2

**Comment by demarey** [comment]
You're right, you should tests PL 2 alpha: https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/feature%252Fspec2/lastSuccessfulBuild/artifact/.
There is now a mysources.list file in addition of the official sources that do no get overwritten.
More details: https://pharo-project.github.io/pharo-launcher/templates/

<blockquote><img src="/pharo-ci-jenkins2/static/2f304bb4/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/feature%252Fspec2/lastSuccessfulBuild/artifact/">Artifacts of feature/spec2 #196 : / [Jenkins]</a></strong></div></blockquote>
<blockquote><img src="../img/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo-project.github.io/pharo-launcher/templates/">Templates - Pharo Launcher documentation</a></strong></div></blockquote>
