### ISSUE TITLE
Unchecking "Quit on launch" and clicking Store Settings has strange consequences

### ISSUE THREAD

**Issue by dupriezt** [pharo-project/pharo-launcher#44]
On Linux Ubuntu 16.04 LTS

Steps to reproduce:
* Downloaded latest-linux.zip from https://ci.inria.fr/pharo/view/Launcher/job/Publish-Launcher-stable-Linux/  (build #53)
* Removed the settings file system-settings.ston to prevent interferences.
* Ran the image
* Observation: Quit on Launch setting checkbox is checked
* Observation: Enable development environment setting checkbox is not checked
* Unchecked Quit on Launch
* Clicked Store Settings
* Killed the image from terminal (without saving it)
* Re-ran the image
* Observation: Another, smaller, PharoLauncher window opened immediately
* Observation: Quit on Launch setting checkbox is still checked
* Observation: Enable development environment setting checkbox is checked
* Trying to close the pharoLauncher image OS window by clicking on the OS cross button throws a "#ifTrue:ifFalse was sent to nil" exception. This message is sent to the "Save" class variable of the PhLDeploymentScript class, which is nil.

**Comment by demarey** [comment]
The problem is that "Quit on Launch" checkbox on the main window is not always reflecting the state of the setting with the same name.

**Comment by demarey** [comment]
Name: PharoLauncher-Core-ChristopheDemarey.155
Author: ChristopheDemarey
Time: 10 January 2018, 8:13:51.701945 am
UUID: b0dea982-c81e-0d00-be3f-7db202f3751b
Ancestors: PharoLauncher-Core-ChristopheDemarey.154

Add an announcement to PhLLaunchCommandClass to announce that the QuitOnLaunch value changed.

---
Name: PharoLauncher-Spec-ChristopheDemarey.58
Author: ChristopheDemarey
Time: 10 January 2018, 8:15:17.257156 am
UUID: 9d56c387-c81e-0d00-be40-397f02f3751b
Ancestors: PharoLauncher-Spec-ChristopheDemarey.57

Register to PhLQuitOnLaunchValueChanged announcement to refresh corresponding checkbox
