### ISSUE TITLE
Scrolling and clicking on image update the list too much

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#444]
![2020-04-06 16 12 21](https://user-images.githubusercontent.com/9519971/78568394-57792600-7822-11ea-98cc-25882dfbf87a.gif)

As we can see on this gif, scrolling and clicking on an image mess up with the list position. It put the image as the first line. This make it quite difficult to double click.

**Comment by demarey** [comment]
The issue is related to a recent update in Spec. See https://github.com/pharo-spec/Spec/issues/866

**Comment by demarey** [comment]
Fixed. See https://github.com/pharo-spec/Spec/pull/868
