### ISSUE TITLE
Launching a 32bits image in not capable system does not give feedback

### ISSUE THREAD

**Issue by tesonep** [pharo-project/pharo-launcher#449]
**Describe the bug**
When you are using an OSX version that does not support anymore 32bits applications (like Catalina 10.15.4). Pharo Launcher does not give nor error or feedback about the opening of an invalid image. Of course, it does not open the image.

**To Reproduce**
In a 64bits only system.
1. Download a new 32bits image.
2. Double click in the image or press the run button
3. (Nothing happens)

**Expected behavior**
The image cannot be executed, so a message when trying to open the image saying that it cannot be done because the system does not support 32bits application.

**Version information:**
 - OS: OSX
 - Version: 10.15.4

**Comment by demarey** [comment]
Pharo Launcher now watchs exit status and give the error message as feedback if any
