### ISSUE TITLE
Image crashes on imageVersionDeterminationScript

### ISSUE THREAD

**Issue by mabdi** [pharo-project/pharo-launcher#454]
**Describe the bug**
Executing the following code results the Pharo image crashes.

**To Reproduce**
```
vmManager := PhLVirtualMachineManager new.
scriptPath := vmManager imageVersionDeterminationScriptPath.
tmp_VfFVf1Jhwf1 := vmManager imageVersionDeterminationScript.
```

**Expected behavior**
I don't know what the code is doing! it's produced by an automatic tool. but I know the image mustn't crash.

**Version information:**
 - OS: Ubuntu + Mac 
 - Version: Pharo 8
 - Commit: e7ef4f0ff4701781e862c50afeb26508cf019fe5

**Comment by demarey** [comment]
Thanks for the report.
With this code, the image is not crashing but exiting (without notification).
As you can see in PhLVirtualMachineManager>>#imageVersionDeterminationScript, there is a call to `Smalltalk snapshot: false andQuit: true`:
```smalltalk
imageVersionDeterminationScript
	| imageFolder |

	SystemVersion current major isNil "Pharo 1.1"
		ifTrue: [ SystemVersion current major: 1. 
					SystemVersion current minor: 1 ]. 

	(SystemVersion current major = 1 and: [ SystemVersion current minor < 4 ])
		ifTrue: [ imageFolder := (Smalltalk at: #FileDirectory) on: Smalltalk imagePath.
			imageFolder forceNewFileNamed: 'pharo.version' do: [ :stream |
				stream 
					<< SystemVersion current major;
					<< SystemVersion current minor ] ]
		ifFalse: [ imageFolder := Smalltalk imagePath asFileReference. 
			SystemVersion current major = 1
				ifFalse: [ imageFolder := imageFolder parent ].
			imageFolder / 'pharo.version' 
				writeStreamDo: [ :stream | |major minor|
					major := SystemVersion current major.
					minor := SystemVersion current minor.
					"Pharo 6 images >= 60509 need 61 VM, even though the image states 60"
					(major = 6 and: [ SystemVersion current highestUpdate >= 60509 ])
						ifTrue: [ minor := 1 ].
					stream 
						<< major asString;
						<< minor asString ] ].
	Smalltalk snapshot: false andQuit: true
```
This code is used to determine the pharo version of an image. It is not intended to be executed by the user in an image but by pharo launcher on another image.
It is part of the process of launching an image (first step) as you can see here: https://pharo-project.github.io/pharo-launcher/contribute/#what-does-the-pharo-launcher-to-launch-an-image

Just curious why you executed this code?

<blockquote><img src="../img/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo-project.github.io/pharo-launcher/contribute/#what-does-the-pharo-launcher-to-launch-an-image">Contribute - Pharo Launcher documentation</a></strong></div></blockquote>

**Comment by mabdi** [comment]
Thank you for your answer. I'm working on a test amplification tool (https://github.com/mabdi/small-amp). This tool transforms existing test methods to increase test coverage (mutation coverage).

In this transformation, first, we generate new test methods by applying a random change (adding a new method call or changing a value, ...) then, we regenerate the assert statements.

During an amplification run, a call to `imageVersionDeterminationScript` was added to `testImageVersionDeterminationScriptIsUpdatedWhenFileContentDifferentFromScriptInImage`, and the process was lost. I misunderstood it was a crash.

So, it's not a bug. It's a special case. 

<blockquote><img src="https://avatars2.githubusercontent.com/u/3696683?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/mabdi/small-amp">mabdi/small-amp</a></strong></div><div>Test Amplification for Pharo. Contribute to mabdi/small-amp development by creating an account on GitHub.</div></blockquote>
