### ISSUE TITLE
PharoLauncher showing Pharo 9 - but not each detailed built image

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-launcher#455]
See https://github.com/pharo-project/pharo/issues/5841

**Comment by demarey** [comment]
Thanks for the report. I did not notice it.
Solved in ec9cda0e4dae2bcd1a7d3bf4cdb95537a16d425e.
I updated the file on files.pharo.org.
If you restart Pharo Launcher (or force the source update from settings), you should have it.

**Comment by astares** [comment]
Confirm that it works! This is a big help for P9 development. Thanks @demarey 

Would be nice if the user could add custom template categories for own builds in the future.

**Comment by demarey** [comment]
@astares It is already doable. Did you check https://pharo-project.github.io/pharo-launcher/templates/#create-your-own-list-of-template-categories?

<blockquote><img src="../img/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo-project.github.io/pharo-launcher/templates/#create-your-own-list-of-template-categories">Templates - Pharo Launcher documentation</a></strong></div></blockquote>

**Comment by astares** [comment]
@demarey Ahh .. cool. Thanks!
