### ISSUE TITLE
Open a Pharo Image From Disk

### ISSUE THREAD

**Issue by chicoary** [pharo-project/pharo-launcher#456]
![open a pharo image dialog](https://user-images.githubusercontent.com/7659991/79696649-75984a80-8254-11ea-8ad0-4e81e70e18d4.png)
![an error occurred when opening a pharo image from disk](https://user-images.githubusercontent.com/7659991/79696659-7fba4900-8254-11ea-9599-774cbd44386b.png)

**Comment by demarey** [comment]
Thanks for the report.
This command missed a test. Now solved
