### ISSUE TITLE
Pharo image won't launch from PharoLauncher when its directory copied by external tools

### ISSUE THREAD

**Issue by eftomi** [pharo-project/pharo-launcher#459]
**Describe the bug**
Pharo image won't launch from PharoLauncher when its directory is copied to another Windows 10 computer by external tools. 

**To Reproduce**
1. PharoLauncher 2.0 installed on two Windows 10 machines
2. Images, VMs located on the pyhsical path "C:\PHARO\images", "C:\PHARO\vms"
3. You create an image on first machine, launch it and save & exit
4. You copy the image folder as is to the second machine (by hand or by sync software) to the above location.
5. PharoLauncher on the second machine sees the image, but it cannot launch it (nothing happens). 
6. The same happens if you create an image on the second computer and copy the folder to the first computer.
6. If you delete meta-inf.ston, PharoLauncher builds a new one and launching succeeds.

**Expected behavior**
The image should launch on the second computer.

**Screenshots**

**Version information:**
 - OS: Windows 10 
 - Version 10.0.18362.778 on both computers

I'm attaching meta-inf files for two images, one is created on 1st computer, the second on the 2nd computer.

[1..zip](https://github.com/pharo-project/pharo-launcher/files/4504667/1.zip)
[2.zip](https://github.com/pharo-project/pharo-launcher/files/4504668/2.zip)

**Comment by eftomi** [comment]
Hm, after some more tests it started to work as it should - I apologize for the nuissance. 

However, the previous version of PharoLauncher worked also when the images were in the users "home" directory, which was different on different machines - in this case the description is as above, except that the folders are different, for instance

1. computer:
"C:\Users\eftomi.DOMAIN\EFTOMI\PHARO\images"
"C:\Users\eftomi.DOMAIN\EFTOMI\PHARO\vms"

2. computer
"C:\Users\tomaz\EFTOMI\PHARO\images"
"C:\Users\tomaz\EFTOMI\PHARO\vms"

**Comment by demarey** [comment]
@eftomi Could you tell me if this Pharo Launcher version https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/dev/ fit your needs?

<blockquote><img src="/pharo-ci-jenkins2/static/493072d5/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/dev/">dev [PharoLauncher-Pipeline] [Jenkins]</a></strong></div></blockquote>

**Comment by eftomi** [comment]
Hi @demarey, thanks for your efforts. I did the test in this way:
1. installed launcher from the address you gave, on one clean machine (Win10 x64)
2. mounted USB memory stick on **D: drive**
3. in launcher settings I set the location of template source files, image init scripts, images and VMs to **D:\PHARO** subfolders (scripts, images, vms)
4. created a new Pharo image (8.0), launched it and save & exit
5. installed launcher from the address you gave, on a second clean machine (Win10 x64)
6. mounted the above USB memory stick on its **F: drive**
7. in launcher settings I set the location of template source files, image init scripts, images and VMs to **F:\PHARO** subfolders (scripts, images, vms)
8. if I select the image created on the first machine, nothing happens when I click Launch.
9. I then created a new Pharo image on this second machine, launched it, and save & exit.
10. then I mounted the USB memory stick back to the first machine. It opens the VM created on this machine flawlessly, but not the VM created on the second.

**Comment by demarey** [comment]
ok. I see why. With customized paths, it could not work.
Can you give a try to https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/dev/ (new version using locators for customized paths)?

<blockquote><img src="/pharo-ci-jenkins2/static/493072d5/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/dev/">dev [PharoLauncher-Pipeline] [Jenkins]</a></strong></div></blockquote>

**Comment by eftomi** [comment]
Hi, I tested it using the same procedure, and it works! Thanks.

**Comment by demarey** [comment]
Nice!
