### ISSUE TITLE
After import it is not possible to access import and other buttons

### ISSUE THREAD

**Issue by Ducasse** [pharo-project/pharo-launcher#461]
**Describe the bug**
After import it is not possible to access import and other buttons

**To Reproduce**
- import a project and you get 
![Screenshot 2020-04-21 at 21 00 57](https://user-images.githubusercontent.com/432549/79980576-986c6e00-84a3-11ea-9a6b-b3642ec85c43.png)

**Version information:**
 - Version: new laucnher in Spec20

**Comment by demarey** [comment]
The bug only concerns the 'import' and 'launch from disk' button.
Other buttons are not available since there is no image selection.
