### ISSUE TITLE
Font size preference not preserved across restarts

### ISSUE THREAD

**Issue by eMaringolo** [pharo-project/pharo-launcher#466]
**Describe the bug**
When you set a different font size (e.g. "medium") in the Settings -> Appeareance, and then restart the launcher, such setting is lost, even if you click on "Store settings".

**To Reproduce**
1. Go to Settings > Appearance
2. Change font size
3. Store settings
4. Click on "Quit"
5. Start Launcher again
6. Font size is ignored.

**Expected behavior**
I expect all the appearance settings to be preserved between launches.

**Comment by demarey** [comment]
Hi,

Sorry for the late answer.
Indeed, if you check the code that is called from GraphicFontSettings fontSizeRow, you see that the font size is applied on the image but there is no setting stored.
It is applied in GraphicFontSettings>>#setFontsToStyleNamed:

In fact, Font size is not a real setting.
You can open an issue on Pharo issue tracker for it if you want.
For PharoLauncher, I would recommand to go for a startup script.
You can write a .st file and put it in FileLocator preferences / pharo-launcher folder.
As you can see here: https://github.com/pharo-project/pharo-launcher/pull/439/files, it is a hidden feature.

<blockquote><img src="https://avatars1.githubusercontent.com/u/9519971?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-launcher/pull/439">allow-manual-settings by jecisc · Pull Request #439 · pharo-project/pharo-launcher</a></strong></div><div>This allows one to write .st files with startup actions to customize the launcher at launch.</div></blockquote>
