### ISSUE TITLE
Would be great to be able to create a one-click image from the launcher

### ISSUE THREAD

**Issue by bergel** [pharo-project/pharo-launcher#467]
**Is your feature request related to a problem? Please describe.**
Deploying a Pharo application is complex. And using the launcher to open an external image is clearly not the way to deploy a professional application. Having a button that create a one click distribution, for the 3 major platform would be fantastic.

**Describe the solution you'd like**
Right click on an image and produce a one-click image

**Describe alternatives you've considered**
Nothing so far.

**Expected development cost**
I imagine that the cost should be pretty low if there are some template about the one-click image available and produced by Jenkins.
I would be happy to help.

**Comment by Ducasse** [comment]
Alex I think that 
- first nowadays app should be signed and differently on each platform so the one click all platform would still require to have to get at least windows and mac signed. 
- Second there are not 3 platforms but *unxes flavor

I think that we good approach and this is independent from the launcher is 
- first have an DeployableApplicationBuilder with subclasses for each platform
- probably looking at cruiser for windows
- then we could have a travis script that build the app before the signing. 

I would love to see these points moving but we are really super super busy.

**Comment by bergel** [comment]
Probably I have underestimated this issue. But it is supper important

**Comment by svenvc** [comment]
The purpose of the Pharo Launcher is not to help build one-click images. 

That used to be pretty straightforward but has been very difficult for years now.

The Pharo Launcher already has to deal with lots of cross platform issues as well as first time user expectations.

**Comment by bergel** [comment]
Okay, so let's close this issue :-)

**Comment by demarey** [comment]
I agree with comments. I would gladly add the ability to package images for distribution into Pharo Launcher if there is already a library doing that. But I think this library should not be part of Pharo Launcher. You could use it independently. Building distributions is not an easy task, each operating system coming with its own requirements. For sure, such a library would be useful. Maybe you could ask to the consortium, pharo board if this library could be put on the roadmap.
