### ISSUE TITLE
An error occurs when accepting to update the templates sources 

### ISSUE THREAD

**Issue by chicoary** [pharo-project/pharo-launcher#470]
![pharo launcher update vailable for templates sources](https://user-images.githubusercontent.com/7659991/81019385-efc3f400-8e3c-11ea-8163-771c3a322088.png)

![pharo launcher file does not exists](https://user-images.githubusercontent.com/7659991/81019397-f5213e80-8e3c-11ea-8989-6d04a53e302c.png)

**Comment by demarey** [comment]
Thank you for the report.
Could you tell me on which OS you are running Pharo Launcher?
Is the problem reproducible? If so, could you click on debug and post here the window title and the stack trace?
