### ISSUE TITLE
Development Mode Not Respected

### ISSUE THREAD

**Issue by seandenigris** [pharo-project/pharo-launcher#473]
**Describe the bug**
When Launcher is opened with development mode enabled, it hijacks the World and resists being minimized or resized, and then doesn't save the image when it quits, making it very hard to do other things or work on it. The only time I noticed development mode not being respected in 1.9.x was when launcher updated itself, when it would reset the theme and open maximized (but still with window toolbar). This was slightly annoying, but less frequent and less severe.

**To Reproduce**
1. Enable development mode
1. Open Launcher from world menu; it clears the World of any other windows and opens itself fullscreen without a window toolbar, making it hard to close (Morphic halos are needed). 
1. Press Launcher's "Quit" button; the image quits without saving, unlike in 1.9.x where it was saved, and you're back to where you started.

**Expected behavior**
When development mode is enabled, the 1.9.x behavior of opening like any other tool (i.e. in a regular window, not maximized) and saving on quit seemed to make more sense.

**Screenshots**
https://youtu.be/fqMM3uIZOaM

**Version information:**
 - OS: MacOS Mojave
 - Version: 2.0.0

**Expected development cost**
Not Sure. I can help, but wanted to at least make sure this was not done on purpose

**Additional context**
None

**Comment by seandenigris** [comment]
Per @demarey on Discord:

> A quick answer for now. Launcher opening in full world can be avoid by executing 'PharoLauncherApplication open' instead of 'PharoLauncherApplication openInWorld'

`PharoLauncherApplication` DNU `#openInWorld`, but both `PharoLauncherApplication open` and `PharoLauncherApplication openFull` seem to do the same thing...

I see the problem now. Since Launcher uses a singleton, once `#beOpenedInWorld` is set, it remains so, and can't be undone. Fix incoming...

**Comment by seandenigris** [comment]
On a side note, I liked in the previous version where Launcher would pop up a playground with the snippet to reopen it in non-fullscreen mode...

**Comment by demarey** [comment]
@seandenigris the playground is still open (at least for me).
You do not see it?

![Capture d’écran 2020-05-18 à 16 18 44](https://user-images.githubusercontent.com/2494203/82223753-5d831c00-9923-11ea-91d9-94e7c9834cfe.png)

**Comment by demarey** [comment]
Looks ok now. I will close the bug. Please open a new one if you see a problem.
