### ISSUE TITLE
Unable to update template: file missing

### ISSUE THREAD

**Issue by sanjayminni** [pharo-project/pharo-launcher#487]
OS: Windows 10 
On starting PharoLauncher I get message in popup

"Update available for Pharo Launcher template sources!"
[Update] [Remind me later]

if I select [Update] then Error popups
FileDoesNotExistException:
'C:\Users\xxxx\Documents\Pharo\sources.list.dl'
[Debug]  [Ignore]

**Comment by demarey** [comment]
Thanks for the report.
Could you tell me which version of Pharo Launcher you use? You can get it by clicking on the "about" button in the toolbar

**Comment by demarey** [comment]
duplicate of #470
