### ISSUE TITLE
Delete command deletes the wrong images

### ISSUE THREAD

**Issue by badetitou** [pharo-project/pharo-launcher#491]
**Describe the bug**
The delete button deletes the wrong image if we sort the table

**To Reproduce**
1. Sort the table with all the images
2. Delete 
3. The dialog shows that the image to delete is not the correct one

**Expected behavior**
The selected image should be deleted

**Screenshots**
![bugDeleteButton](https://user-images.githubusercontent.com/6225039/82801945-64a7ae00-9e7e-11ea-9112-f4a1c2c5541c.gif)

**Version information:**
- Pharo Launcher version: e4df610

**Expected development cost**
1/2 hours? Maybe more depending on the model

**Comment by demarey** [comment]
The bug is coming from Spec. See https://github.com/pharo-spec/Spec/issues/889
