### ISSUE TITLE
Choose template list should be single selection

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#492]
Today I missclicked and did a `cmd + a` in the list of template selection in the new image dialog and it selected the full list. Then when I validated the launcher raised an error popup. 

I think this list should be single selection.

**Comment by demarey** [comment]
multi-selection is enabled to allow removal of several templates at the same time (only valid for local templates)

**Comment by demarey** [comment]
I will close the issue. I think it is better now. Tell me if you have a better idea.
