### ISSUE TITLE
Pharo-Launcher doesn't work on NixOS

### ISSUE THREAD

**Issue by nova-nowiz** [pharo-project/pharo-launcher#504]
**Describe the bug**
Pharo-Launcher doesn't work on nixos. The bash files are not general enough

**To Reproduce**
1. Download Linux Pharo-Launcher from the main website
2. Try Launching it
3.You will get:
```
/home/narice/hdd/dev/pharo/pharolauncher/pharo-vm/pharo: line 4: /usr/bin/dirname: No such file or directory
/home/narice/hdd/dev/pharo/pharolauncher/pharo-vm/pharo: line 29: /usr/bin/ldd: No such file or directory
/home/narice/hdd/dev/pharo/pharolauncher/pharo-vm/pharo: line 29: /bin/fgrep: No such file or directory
Error. Could not determine platform's libc path for VM.
Try forcing $PLATFORMLIBDIR in /home/narice/hdd/dev/pharo/pharolauncher/pharo-vm/pharo, based on LIBC_SO.
Please report what works to pharo [vm-dev] mail list.
  LIBC_SO=
  NAME=NixOS
  ID=nixos
  VERSION="20.09pre239318.c59ea8b8a0e (Nightingale)"
  VERSION_CODENAME=nightingale
  VERSION_ID="20.09pre239318.c59ea8b8a0e"
  PRETTY_NAME="NixOS 20.09 (Nightingale)"
  LOGO="nix-snowflake"
  UNAME=Linux narice-pc 5.4.59 #1-NixOS SMP Wed Aug 19 06:16:29 UTC 2020 x86_64 GNU/Linux
  System seems to be 64 bit. You may need to (re)install the 32-bit libraries.
```

**Expected behavior**
Pharo Launcher should launch.

**Version information:**
 - OS: NixOS
 - Version: 20.09

**Expected development cost**
This shouldn't be a very hard fix.
I'm willing to help as Pharo seems like a very interresting language and I would be happy to test it ;)
I'm posting this issue first as I don't know when I'll do it.

**Additional context**
NixOS has a very special file structure. it doesn't have a /usr/bin or a /bin. But this can be fixed using more general things.
For example, instead of using /usr/bin/bash, you use /usr/bin/env bash. This is more general than /usr/bin/bash. It shouldn't break compatibility with other linux distros either!

**Comment by nova-nowiz** [comment]
this is not a bug, it is due to how applications are installed on nixos. I had not enough experience with nixos at the time of writting this issue
what I said in the additional context section is still valid and would be appreciated but I'm closing the issue.

**Comment by AlexChalk** [comment]
@Narice did you get this working?

**Comment by Falderian** [comment]
> @Narice did you get this working?

Hi, for there was enough just install the official nix package.
[pharo package](https://search.nixos.org/packages?channel=25.05&show=pharo&from=0&size=50&sort=relevance&type=packages&query=pharo)
