### ISSUE TITLE
[Feature Request] Multiple sources.list

### ISSUE THREAD

**Issue by badetitou** [pharo-project/pharo-launcher#506]
Currently, by default we use the sources.list of file of pharo.org.
If we want to add our own distribution, we have to duplicate this file locally and then update it.
Thus, we do not get the automatic update of the file online.

It would be nice if we can select more than one source.list (so we can have several source comming from pharo.org, locally, _etc_)

**Comment by demarey** [comment]
Already available.
See https://pharo-project.github.io/pharo-launcher/templates/#create-your-own-list-of-template-categories
