### ISSUE TITLE
[Feature Request] Add an "Update all" button to VM Manager

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-launcher#512]
I have many VMs installed - like Pharo 7, 8 and 9 as regular 64 and 32 bit and as headless version,

![image](https://user-images.githubusercontent.com/5980033/106129379-7acde280-6160-11eb-8ee5-7ab76ac8e6ec.png)

To update them one has to **manually update each of them** - which mean a lot of clicks.

It would be really nice to have an "Update all" button to update them all sequentially but with a single click

**Comment by demarey** [comment]
in latest version (spec 2), you can do a multiple selection and click update.
