### ISSUE TITLE
"Show in Folder" not functionning on Mac OS 11.2 Big Sur

### ISSUE THREAD

**Issue by bouraqadi** [pharo-project/pharo-launcher#513]
**To Reproduce**
1. Right Click on any image
2. You get the user home folder instead of the folder of the selected image

**Version information:**
 - OS: Mac OS
 - Version: 11.2 Big Sur

**Comment by demarey** [comment]
Hi Noury,

Thank you for reporting.
Unfortunately, I do not have Big Sur to test this problem.
Pharo Launcher does almost nothing by running a shell command: `open some_path`.
Could you put a breakpoint in PhLFileBrowser>>#visitMacOS: and see the command that is executed?
Path should be correct. If so, try to run the same command from a terminal, if not then we should debug the path coming to this method.

**Comment by bouraqadi** [comment]
The command line is correct
```open ""<pathToImageFolder>""```
By accident, I had the finder in list mode and it worked. Switching back column mode I get the bug.
I get the same behavior from a terminal.
Conclusion: This is a MacOS bug.
