### ISSUE TITLE
Not able to launch pharo 9.0 64bit stable on windows

### ISSUE THREAD

**Issue by wayahead** [pharo-project/pharo-launcher#523]
When launch pahro 9.0 64bit stable on windows 10, error downloading happened. The reason is pharolauncher uses wrong vm filename "pharo-vm-Windows-X86_64-stablezip" to download file pharo-vm-Windows-x86_64-stable.zip.

**Comment by demarey** [comment]
Thank you for the report. I did not notice it.
I will upload a new version with the fix ASAP.

**Comment by wayahead** [comment]
Thx a lot!
