### ISSUE TITLE
There is no vm for Pharo 10 available to download

### ISSUE THREAD

**Issue by jordanmontt** [pharo-project/pharo-launcher#524]
Error when downloading and launching a Pharo 10 image.

If you download a Pharo 10 image and try to launch it there is this error message and you cannot run the image:
![Screenshot 2021-07-19 at 16 14 04](https://user-images.githubusercontent.com/33934979/126174517-ec0900ce-eefe-4aed-b400-b73012040756.png)
This is because there is no vm for Pharo 10 available to download:
![Screenshot 2021-07-19 at 16 16 31](https://user-images.githubusercontent.com/33934979/126174679-6d8a5f5c-78cf-470f-b861-919dbb2b0c23.png)

If you run the Pharo 10 image with the Pharo 9 vm runs without problem.

**Comment by demarey** [comment]
Hi

Did you try with th me latest version of pharo launcher? Because URLs are not the same since pharo 9 and old pharo launcher do not handle them.

**Comment by jordanmontt** [comment]
I clicked the update button when the message "Pharo launcher has a new version" appeared. But now I reinstalled the pharo launcher and there is no problem anymore.
