### ISSUE TITLE
Pharolauncher freezes frequently after update to MacOS Monterey

### ISSUE THREAD

**Issue by jbrichau** [pharo-project/pharo-launcher#533]
**Describe the bug**
After upgrading to MacOs Monterey, a running Pharolauncher image sometimes freezes after awaking my laptop from sleep. I need to force quit it since it's totally unresponsive to clicks. 

I did not see the same with running Pharo images, so it seems specific to the PharoLauncher image. 

**To Reproduce**
Sorry, hard to reproduce. It happens 1 out of 3 times after waking the laptop from sleep.

**Expected behavior**
The Pharolauncher image should just be responsive to clicks/commands.

**Version information:**
 - OS: MacOs 12.0.1
 - Pharolauncher version: 2.3-2021.07.12

**Comment by jbrichau** [comment]
Correction: I can just quit the Pharo launcher by clicking the close button on the window. No 'Force quit' is required.

**Comment by jbrichau** [comment]
Update: it seems that the image is still working but the UI does not get redrawn. When double click an item in the list of image, the image gets started. However, I do not see any update in the UI of the Pharolauncher and I do not know how I can start debugging that.

**Comment by Bajger** [comment]
@jbrichau : Hi! Could you check and try to reproduce with latest Pharo launcher 3.0?

**Comment by jbrichau** [comment]
Hi @Bajger 
I have not experienced this anymore with version 3.0

Closing this report. Thanks!
