### ISSUE TITLE
Pharo Launcher portable version for Windows

### ISSUE THREAD

**Issue by ELePors** [pharo-project/pharo-launcher#534]
A portable version of pharo launcher should be a very interresting feature for Windows. A Zip package delivery for example.
The MSI installer is sometimes blocked when you are not administrator of you Windows session.

**Comment by labordep** [comment]
Yes ! :)
I haven't the possibility to execute (and also download) the Pharo Launcher from my enterprise desktop (due to proxy restrictions and no admin account).
But with a Portable version this is possible to run an .exe file in a specific folder, this way exclude installation, so if the PharoLauncher is directly executable this is great !

**Comment by demarey** [comment]
done

**Comment by astares** [comment]
For the records:   https://github.com/pharo-project/pharo-launcher/releases/tag/3.2
includes [pharo-launcher-3.2.msi](https://github.com/pharo-project/pharo-launcher/releases/download/3.2/pharo-launcher-3.2.msi) and also [PharoLauncher-windows-3.2.zip](https://github.com/pharo-project/pharo-launcher/releases/download/3.2/PharoLauncher-windows-3.2.zip)

<blockquote><img src="https://opengraph.githubassets.com/8deb9379e8395c145226f8839de5439c7068daae3e4da0b683adc9312613a870/pharo-project/pharo-launcher/releases/tag/3.2" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/pharo-project/pharo-launcher/releases/tag/3.2">Release Pharo Launcher 3.2 · pharo-project/pharo-launcher</a></strong></div><div>Changelog
Pharo Launcher now comes with a command-line version that you can use from a terminal!
You can check the documentation of commands at https://pharo-project.github.io/pharo-launcher/comman...</div></blockquote>
