### ISSUE TITLE
recreate the image does not re apply the script if one is provided

### ISSUE THREAD

**Issue by hogoww** [pharo-project/pharo-launcher#536]
**Describe the bug**
When recreating the image, it only redownload the image.
If a script is provided however, it is only applied the first time around, and not reset upon recreating it.

**To Reproduce**
1 Create a new image with a script.
2 Launch the image, the script is *executed*.
3 Quit.
4 Recreate the image using the menu
5 Launch the image : The script is *not executed*

**Expected behavior**
The script should be executed after recreating an image

**Version information:**
Ubuntu 20
Pharo 9
Pharo Launcher version: 2.2

**Expected development cost**
Should be fairly easy.
I'm assuming it's just a flag to reset.
I will probably look into it when I get time.

**Comment by demarey** [comment]
fixed by #542
