### ISSUE TITLE
Test failing in STON on Latest dev version

### ISSUE THREAD

**Issue by hogoww** [pharo-project/pharo-launcher#538]
**Describe the bug**
The test  PhLRecreateImageCommandTest >> #testCanRecreateAnImage fails with a STON reading error.

**To Reproduce**
Run the test case : PhLRecreateImageCommandTest >> #testCanRecreateAnImage 

**Expected behavior**
passing test case

**Screenshots**
![image](https://user-images.githubusercontent.com/21278554/150329076-ae1fa6e1-1231-4c22-b60d-1b3ce3e97337.png)

**Version information:**
OS : Ubuntu 20
Commit PharoLauncher fb77b62e406341350929ecd637ad65e38c95af65

**Expected development cost**
No idea, I tried to track it down but I do not know.
Looks like it is in the mock images created for the test cases.

**Comment by demarey** [comment]
cannot reproduce  in Pharo 10 branch
