### ISSUE TITLE
Cannot launch an image in the non-default location

### ISSUE THREAD

**Issue by apblack** [pharo-project/pharo-launcher#54]
A colleague gave me a launcher image folder on a memory stick.  I can't launch it from the launcher without first copying it into my default images folder.

**Comment by demarey** [comment]
In Pharo Launcher settings, you could change the 'Location of your images' setting to point to the folder on the USB stick.
Anyway, I think it would be nice to launch an image not in the default folder so I added this feature:

Name: PharoLauncher-Core-ChristopheDemarey.152
Author: ChristopheDemarey
Time: 5 January 2018, 11:08:12.216335 am
UUID: b3c6f35c-661e-0d00-b0c2-4b020bea67e1
Ancestors: PharoLauncher-Core-ChristopheDemarey.151

fix issue #54 Cannot launch an image in the non-default location.
If no image is selected, and launch button is pressed, then a file selection window is opened and Pharo Launcher lanches the selected file.
