### ISSUE TITLE
Make Pharo Launcher run natively on Mac M1

### ISSUE THREAD

**Issue by Inao0** [pharo-project/pharo-launcher#544]
**Describe the request**
Currently, Pharo Launcher runs on Rosetta for mac with Apple M1 processors.

**Expected behavior**
Ideally, Pharo Launcher would run natively on Apple M1.

**Expected development cost**
This would require using another version of Pharo for running the launcher. Maybe put two Mac OS buttons on the Pharo website to download the one corresponding to the architecture.
I am willing to help but have no knowledge of how the Pharo launcher works.

**Screenshots**
![Screenshot 2022-03-14 at 11 11 23](https://user-images.githubusercontent.com/37711386/158151555-2a122e12-e129-4743-aee9-3b33a89b1f65.png)

**Expected behavior**
"Kind" column should show Apple, like for the Pharo process

**Version information:**
 - OS: macOS Monterey
 - Version: 12.0.1 (21A559)
 - CPU: Apple M1

**Comment by demarey** [comment]
done in 2b89478eb6fa97a3082121f26cfdc5f9691928de

**Comment by cperezabo** [comment]
Do you know when is it going to be released?

**Comment by demarey** [comment]
> Do you know when is it going to be released?

It is a matter of days.
A beta version is available here:  https://files.pharo.org/pharo-launcher/beta/ 


<blockquote><img src="/_h5ai/client/images/app-16x16.ico" width="48" align="right"><div><strong><a href="https://files.pharo.org/pharo-launcher/beta/">index · styled with h5ai 0.22.1 (http://larsjung.de/h5ai/)</a></strong></div><div>index styled with h5ai 0.22.1 (http://larsjung.de/h5ai/)</div></blockquote>
