### ISSUE TITLE
[Beta] Development mode does not close pharoLauncher application

### ISSUE THREAD

**Issue by hogoww** [pharo-project/pharo-launcher#548]
**Describe the bug**
Development mode leaves the application windows in the background, with no mean to close it.

**To Reproduce**
1 Launch pharo launcher
2 Set the development mode setting to true
3 The applications does not close, although the playground shows up

**Expected behavior**
The application should close and the playground should show up.
This was the previous behavior

**Screenshots**
![Screenshot 2022-04-07 at 12 53 01](https://user-images.githubusercontent.com/21278554/162183347-aed2452f-06df-4c18-b351-1caa9bf90b48.png)

**Version information:**
MacOs catalina

**Comment by demarey** [comment]
Thanks for the report.
[completed](https://github.com/pharo-project/pharo-launcher/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/pharo-project/pharo-launcher/commit/9dbe6eb421262232a02871b71e60f704d02693e0
