### ISSUE TITLE
Display name of Pharo 7 images unusable

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#55]
Reported by @astares :
The downloadable files for Pharo 7 are not correctly displayed (see Screenshot attached). 

I guess this is because the image file names have changed (initially the build process was set up 
to include the git hash but now we also have the build number returned again, see [1])

So with the current Launcher one can not directly load a specific build number for Pharo 7 or see which
build number is the latest available. So for Pharo 7 it is usable to download "latest", "latest-32"
or "latest-64" but it is not possible to really distinguish all the "Pharorpackage-7" entries.

It would be really a step forward if this could be fixed somehow and also for Pharo 7 display the
image build number to make Launcher usable also for contributors to Pharo 7 again.

[1] http://forum.world.st/SystemVersion-cleanup-or-the-return-of-the-explicit-build-number-in-latest-Pharo-7-td4977073.htm

![launcher](https://user-images.githubusercontent.com/2494203/33364960-e73c0e60-d4e6-11e7-9ee7-547ba1d2e7a2.png)

**Comment by demarey** [comment]
should be fixed.
@astares could you confirm it works? If so, I will publish a new version with a couple of other bug fixes.

--------
Name: PharoLauncher-Core-ChristopheDemarey.145
Author: ChristopheDemarey
Time: 29 November 2017, 9:24:20.112852 am
UUID: 7f8b5c99-7c1b-0d00-8b77-298d06ae6069
Ancestors: PharoLauncher-Core-ChristopheDemarey.143

fix #55: Display name of Pharo 7 images unusable

**Comment by astares** [comment]
The build number and hash is now displayed. Still two problems:

 -  display name is now "Pharorpackage" ???
 - the download of such a package fails - at least on Windows

![image](https://user-images.githubusercontent.com/5980033/33365925-14f1089e-d4ea-11e7-9706-92be4de99e41.png)

**Comment by astares** [comment]
Reason seems to be that the Launcher downloads "Pharorpackage-7.0.0-alpha.build.345.sha.d09f8eb.arch.32bit.zip" which is only 93KB in size and includes only
two files:
 - packagesKernel.txt
 - protocolsKernel.txt

So there is no image file inside of the ZIP. I guess the launcher grabs the wrong download.

**Comment by demarey** [comment]
I see, the problem is that there is a lot of "junk" files in pharo7 distributions. Pharorpackage* archives only contains text files with the list of package names. For me all these intermediate files should not be published on the file server. we have far too much data on it, especially when we are able to rebuild them from sources.

**Comment by astares** [comment]
Launcher seem to load from the "bloated" but also "old" file directory which has all these stuff from the build.
If I remember correctly for Pharo 7 the download of the clean image ZIPs is hosted on another place. 

You have to ask Esteban or check what is used zeroconf scripts these days (get.pharo.org)

**Comment by astares** [comment]
i guess zeroconf is using http://files.pharo.org/get-files/70/ which only hosts the latest

**Comment by astares** [comment]
No - you are right. The directory is bloated - so I see too many files. Unfortunately there is no filter capability on the template panel (left side) of Launcher. 

So the general PhLHTTPListingTemplateGroup(class)>>regex is applied which just uses ZIPs.

I guess we need a different regex to filter out the non-related files for Pharo 7.

**Comment by demarey** [comment]
I'm seeing to clean the 70 folders to only keep 32-bits and 64-bits versions of pharo70 and Pharo70Metacelle (minimal image). The later will not be usable by the launcher since it has no UI but I think it is not a big deal.

**Comment by astares** [comment]
No - the problem is that usually only *.zip is filtered. It would make sense to have a possibility for the PhLHTTPListingTemplateGroup to give a pattern per version and have a regex cache per version instead of a single pattern for all.

I just implemented that so one can now write

     self 
		name: 'Pharo 7.0 (development version)' 
		url: 'http://files.pharo.org/image/70/' asZnUrl
		filterPattern: 'href="(Pharo-7.0.0-alpha.build.[^"]*.zip)"'

for me that works. The only issue is that Launcher downloads the image but is not able to
find the windows vm for 64 bit (which is another new issue unrelated to this issue itself)

PLEASE REVIEW AND TEST

----------------------------------------------------------------------------------------------------
Name: PharoLauncher-Core-TorstenBergmann.146
Author: TorstenBergmann
Time: 29 November 2017, 11:31:20.986427 am

UUID: 3bdb995f-7e1b-0d00-8151-d53b06ad13a5
Ancestors: PharoLauncher-Core-ChristopheDemarey.145

Fix the template groups for Pharo 7. One can now give a filter pattern/regex per version group.

pharo70
	^ self 
		name: 'Pharo 7.0 (development version)' 
		url: 'http://files.pharo.org/image/70/' asZnUrl
		filterPattern: 'href="(Pharo-7.0.0-alpha.build.[^"]*.zip)"'

**Comment by astares** [comment]
Remember that when one just updates the code one need to run:

PhLTemplateGroupRepository resetGroups 

to clear the class variables.

**Comment by demarey** [comment]
With Pavel, we are cleaning the 70 folder on files.pharo.org.
Thanks for the contribution. I think it is a good idea.
For the windows 64-bits vm, it is simple: there is no one available in http://files.pharo.org/get-files/70/

**Comment by demarey** [comment]
Looks good to me. The only drawback is that you will not be able to launch images named http://files.pharo.org/image/70/Pharo7.0-*bit-*.zip (yes, there is 2 different formats). I do not know well Pharo regex but probably we could add it.

**Comment by demarey** [comment]
Thanks for this contribution
