### ISSUE TITLE
Show folder button is broken in Windows 10

### ISSUE THREAD

**Issue by fuhrmanator** [pharo-project/pharo-launcher#551]
**Describe the bug**
Clicking on the Show folder button for an image fails in PL 3.0 - this is a very useful feature in Windows but it now throws a `Instance of Win64Platform did not understand #privShellExplore:` error.

**To Reproduce**
1. Running PL in Windows 10, Select an image
2. Click on the Show (folder) button (icon): 
![image](https://user-images.githubusercontent.com/7606540/163601186-21f6acb9-3320-4286-b911-277703b4fcee.png)
3. See error

**Expected behavior**
Show the folder of the image in the OS (this feature worked fine in PL 2.x, it's a regression)

**Screenshots**
![image](https://user-images.githubusercontent.com/7606540/163601634-6a66a2ea-82c9-46a9-902c-1a0a340b9c91.png)

**Version information:**
 - OS: Windows 10
 - Version: Pharo Launcher 3.0

**Expected development cost**
Unknown, but regressions with different OS could be tested in CI. Windows is a popular platform with end users, even if the devs prefer Linux and MacOS.

**Comment by demarey** [comment]
@fuhrmanator this kind of feature is very hard to test => interaction with the operating system.
The only thing that could be tested is that there is no error on instance side. It is done in a command test but tests are, for now, only ran on linux. Only a few tests are impacted by the OS and I'm not sure it worths to run tests on all OS/arch combinations.
