### ISSUE TITLE
PL UI does not show up on Windows

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#554]
**Describe the bug**
Reported by Renaud de Villemeur:
> I experience some issue on windows (windows 11 pro). The launcher doesn't show up.
> I double click on the icon, and no window appears. I can however see that the process is running in the task manager. I can open the launcher image from the local install of pharo VM 100-x64 (installed using Pharo Launcher 2.4, last update 2022-03-20), and the launcher is working great that way.

**Version information:**
 PL 3.0

**Comment by demarey** [comment]
fixed by ce01dd4486bd241da64e408ca925d0905f192391

**Comment by demarey** [comment]
The pb was the installer instructions were missing some files to be installed into the destination directory

**Comment by Ducasse** [comment]
Cool!
