### ISSUE TITLE
Fix cleanup of PhLProcessWrapperTest>>testRunningInfiniteProcessThrowsTimeout

### ISSUE THREAD

**Issue by Bajger** [pharo-project/pharo-launcher#558]
**Describe the bug**
` PhLProcessWrapperTest>>testRunningInfiniteProcessThrowsTimeout` starts infinite loop process, which is never terminated. Tests passes, but never cleans a process, which is still running. This causes noisy `Hit CTRL+C` output, when running multiple tests.

**To Reproduce**
1. Clone Pharo Launcher 
2.  build pharo launcher: `PHARO=100 ARCHITECTURE=64 ./build.sh prepare`
3. run: ./pharo-vm/pharo --headless ./PharoLauncher.image test "PharoLauncher-Tests-Functional"
4. `Hit CTRL+C` keeps repeating on terminal (caused by `testRunningInfiniteProcessThrowsTimeout`)

**Expected behavior**
Endless loop process is properly terminated after assertion (see test method). 

**Version information:**
 - OS: Ubuntu Lunux
 - Version: Pharo Launcher 3.0.1

**Expected development cost**
Add to test `process terminate` in `ensure: ` block?

**Comment by Bajger** [comment]
@demarey : Should I remove my commit to not interfere with yours? https://github.com/Bajger/pharo-launcher/commit/7307b2215fb54a4d7627002f8b8d5bad3690ce93

**Comment by Bajger** [comment]
Ahh, ignore this PR is already closed.

**Comment by Bajger** [comment]
@demarey Should I close this issue? I think fix is only in feature/cmd-line branch, not sure if to cherrypick your fix to main branch?

**Comment by demarey** [comment]
the issue will close by itself when the cmd-line branch will be merged in the main branch
