### ISSUE TITLE
Dev Mode Should Close Launcher Window

### ISSUE THREAD

**Issue by seandenigris** [pharo-project/pharo-launcher#561]
**Describe the bug**
In 3.0.1, when entering dev mode, the tool doesn't close as it did in previous versions. It's not so easy to close manually because, per @estebanlm, the morph is sticky so the halos don't come up.

**Expected behavior**
The tool should be closed automatically when entering dev mode

**Screenshots**
<img width="1072" alt="Screen_Shot_2022-05-18_at_3 30 41_PM" src="https://user-images.githubusercontent.com/184176/171186425-453b3f3d-15ef-4c68-b5a6-10699d879924.png">

**Version information:**
  - Version: 3.0.1

**Expected development cost**
Minimal

**Comment by hogoww** [comment]
Similar to #548 .
Both should be closed upon fix.

**Comment by demarey** [comment]
Thank you for the report Sean
