### ISSUE TITLE
Using the launcher may break any OSSubProcess commands

### ISSUE THREAD

**Issue by Ducasse** [pharo-project/pharo-launcher#57]
When working with pillar we noticed that the bash was executed without any .bash_profile, or bash_rc 
We tested with and without the launcher.... and the launcher shows that it is the faulty guy.

**Comment by Ducasse** [comment]
@guillep

**Comment by demarey** [comment]
It is not a problem directlry related to Pharo Launcher.
If you launch an app from the GUI, you do not inherit from the bash environment.
Could you test if, after running PharoLauncher from a terminal (bash), your environment is correct?

**Comment by guillep** [comment]
Yeh... but it would be nice to have at least as an option:

 - that the pharo launcher launches pharo inside a shell session to have all env vars available? Otherwise any app needing PATH or other simple env vars may fail!

**Comment by demarey** [comment]
yes, we could add an option for that. it is not a big deal.
But first, it would be good to know if it works nicely when PharoLauncher is run from command line (it should).

**Comment by demarey** [comment]
option implemented:

```
Name: PharoLauncher-Core-ChristopheDemarey.153
Author: ChristopheDemarey
Time: 5 January 2018, 1:24:13.820356 pm
UUID: daf86b43-681e-0d00-b78d-eef90b7bef9a
Ancestors: PharoLauncher-Core-ChristopheDemarey.152

Add the ability to launch image from a forked shell process and add a setting for it.
```

**Comment by demarey** [comment]
From bash man page:

>  When  bash  is  invoked  as  an  interactive  login  shell,  or  as  a  non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists.  After reading that file, it looks for  ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is  readable.  The --noprofile option may be used when the shell is started to inhibit this behavior.
> 
>  When a login shell exits, bash reads and executes commands from the file ~/.bash_logout, if it exists.
> 
> When an interactive shell that is not a login shell is started, bash reads and executes commands from ~/.bashrc, if that file exists.  This may be inhibited by using the --norc  option.  The --rcfile file option will force bash to read and execute commands from file instead of ~/.bashrc.
> 
> When  bash  is  started non-interactively, to run a shell script, for example, it looks for the variable BASH_ENV in the environment, expands its value if it appears there, and uses the expanded value as the name of a file to read and execute.
>  Bash behaves as if the following command were executed: 
> `if [ -n "$BASH_ENV" ]; then . "$BASH_ENV"; fi`
>   but the value of the PATH variable is not used to search for the file name.
>

**Comment by demarey** [comment]
Name: PharoLauncher-Core-ChristopheDemarey.164
Author: ChristopheDemarey
Time: 15 January 2018, 2:41:00.736344 pm
UUID: b9ad6d80-321f-0d00-a491-e2820b978409
Ancestors: PharoLauncher-Core-ChristopheDemarey.163

use a login shell to get user environment
