### ISSUE TITLE
Recreate image should keep some local files

### ISSUE THREAD

**Issue by hogoww** [pharo-project/pharo-launcher#578]
**Describe the bug**
Recreate image removes everything in pharo-local

**Expected behavior**
Pharo-local should be preserved to some extent.
I'm thinking particularly the playground cache & the iceberg repository

**Expected development cost**
small.
I just need feedback before I do it myself.

**Comment by demarey** [comment]
Hi,

The behaviour is not a bug since it was thought to do what is describe:
recreate = create a new image from the same template + the same name, discarding all other files but the image metadata.
I would not change it to keep some files but it could be another action if really needed

**Comment by hogoww** [comment]
That makes sense.
The usecase was when during a sprint I had to recreate the image. over and over, and re clone the repository every time.
And loosing the cached-playgrounds
Maybe another action would be better.
But to me recreate the image could also mean recreate *only* the image, and keep the rest (epicea, iceberg, play cache ect)
