### ISSUE TITLE
primitive #primLoadSymbol:module: in TFFIBackend failed

### ISSUE THREAD

**Issue by clarking** [pharo-project/pharo-launcher#582]
**Describe the bug**
A Debugger window appears when the launcher is started

**To Reproduce**
1. Download pharo launcher for linux
2. Extract in a folder
3. Create a desktop launcher (xfce4) pointing to pharo-launcher script
4. Double Click the launcher

**Expected behavior**
I expected to see the default manager view to launch an image

**Screenshots**
![pharo](https://user-images.githubusercontent.com/8283993/198450813-a4b05854-c876-49be-8a51-3ee18e5c939f.png)

**Version information:**
- Arch Linux x64
 - Linux 6.0.1-arch1-1  SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

Thank you for your support

**Comment by demarey** [comment]
Hi @clarking,

Thank you for the report.
Pharo Launcher Linux bundle does not work out of the box on Linux Arch (problems with libraries version).
Some pharo users are maintaining a package for this OS that will work better: https://aur.archlinux.org/packages/pharo-launcher
In the future, we would like to distribute Pharo Launcher on Linux only with native OS packages to avoid problems.

**Comment by clarking** [comment]
Hi @demarey, 
i didn't know that Arch had a specific package for the launcher, I'm going yo give it a try, and see how it goes. Thank you for your response.

**Comment by demarey** [comment]
Since I got no feedback, I will close the issue. Feel free to re-open it if you still have problems.
