### ISSUE TITLE
Pharo Launcher download yields poor performance on macosx Montery and M1 mac. 

### ISSUE THREAD

**Issue by halfmoongroup** [pharo-project/pharo-launcher#587]
I recently got a new M1 mac.  Shortly after getting it, I went to the Download page on the pharo.org web site and downloaded the Pharo Launcher.  After installation and creating a link to /usr/local/bin/bash  the Launcher will start up an image, but performance is horrible.  I confirmed that his was a configuration problem by creating a new Pharo install from the zero config scripts and that version of Pharo has no performance problems.  In addition new images created with the Pharo launcher also have horrible performance. 

I can open the same image in the VM that was downloaded from the zero conf install  and it is performant. 

**To Reproduce**
Download the Pharo Launcher on an M1 Mac, 
Start an image.
Switching between classes on the caylpso browser takes around 2 seconds.  All actions have a noticeable delay

**Expected behavior**

**Version information:**
 - Mac OS Monterey 12.6.2
 - Pharo 10

**Expected development cost**
Should be low cost to fix this. I'm sure the problem revolves around which VM is downloaded with the PharoLauncher.

**Comment by demarey** [comment]
Thank you for the report.
Did you use the arm64 version of Pharo Launcher (https://files.pharo.org/pharo-launcher/mac-arm64)?
Indeed, using x64 version has poor performances.
Poor performances on launched images depend on the VM used to run images. You can see it by right-click on the image, then `copy launch command` and paste the clipboard content into some text editor or shell. It should use an arm-64 version.
Could you report VM versions found?

**Comment by demarey** [comment]
I suppose the problem is solved by the arm64 version of Pharo Launcher since I got no feedback.
If not, feel free to reopen the issue.
