### ISSUE TITLE
Rename launching file from Pharo to PharoLauncher

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#59]
To launch the PharoLauncher we will use:
- Pharo menu entry on Windows
- pharo script on linux
- Pharo.app on OSX

This is confusing because it does not launch Pharo but the PharoLauncher.

All those files should be renamed to PharoLauncher I think.

**Comment by seandenigris** [comment]
This is in 1.2, no? Should we close?

**Comment by demarey** [comment]
@seandenigris Right. It is implement on Linux, OS X and Windows since 1.2.
