### ISSUE TITLE
PrimitiveFailed: primitive #rename:ifAbsent:to:ifPresent:fileSystem: in MacStore failed

### ISSUE THREAD

**Issue by olekscode** [pharo-project/pharo-launcher#591]
**Describe the bug**

After installing Pharo Launcher for Mac arm64, I open it and get the following error:
```
PrimitiveFailed: primitive #rename:ifAbsent:to:ifPresent:fileSystem: in MacStore failed
```
When I click on `New` button to create an image, I get the same error.
Which means that I can not create images

**Screenshots**

<img width="975" alt="Screenshot 2023-02-10 at 11 10 50" src="https://user-images.githubusercontent.com/8271691/218065128-d412ed30-db87-4ff3-964b-86566eb9ebd1.png">

**Version information:**
 - OS: Mac OS Ventura 13.1 (Apple M1)
 - Version: Pharo Launcher for Mac OS arm64

**Comment by demarey** [comment]
Thank you for the report.
Did you check that the app has enough permissions to run correctly (see https://support.apple.com/en-gb/guide/mac-help/mchl211c911f/13.0/mac/13.0)? 

<blockquote><div>Apple Support</div><div><strong><a href="https://support.apple.com/en-gb/guide/mac-help/mchl211c911f/13.0/mac/13.0">Change Privacy & Security settings on Mac</a></strong></div><div>On your Mac, choose what your computer makes available to others across the internet or a network, and protect your information by encrypting it.</div></blockquote>

**Comment by olekscode** [comment]
Hi @demarey 
Do you know what are the permissions that Pharo Launcher needs?

**Comment by demarey** [comment]
I only have Mac Os 10.14 so I cannot tell you.
Regarding the error, you should check that the app has permission to write files on disk, especially in the Documents folder.

**Comment by olekscode** [comment]
I checked and yes, Pharo Launcher has access to Documents folder:

![Screenshot 2023-02-10 at 16 38 59](https://user-images.githubusercontent.com/8271691/218132571-c455997e-c681-4737-a888-1a58ec628471.png)

**Comment by demarey** [comment]
I will try to find someone with a Mac OS Ventura 13.1 (Apple M1) to see if I can reproduce.

**Comment by olekscode** [comment]
Thank you Christophe!
Let me know if you find something
I really miss Pharo Launcher 🥲

**Comment by olekscode** [comment]
This happens when PharoLauncher generates a file `sources.list.dl.3d3a1e90-0ab1-0d00-9684-a3580e9b7beb` and then tries to rename it to `sources.list.dl`

**Comment by demarey** [comment]
Looks to be fixed in latest version
