### ISSUE TITLE
General progress bar

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#595]
I gave a lesson today where students were using the pharo-launcher. The connection was slow and I noticed a UX problem. 

Currently when we create a new image, a progress bar appears during the download or when extracting the zip. The problem is that between some steps, there is no progress bar. It would be nice to have a two level progress bar to see the general progress of the image creation and know it is not finished after the download because it still needs to extract.

**Comment by Bajger** [comment]
@jecisc: Is this something you'd expect? 
![Peek 2023-04-12 11-56](https://user-images.githubusercontent.com/45875448/231426990-ad9bdb63-0064-420e-855b-b10ecea7b5e2.gif)

**Comment by jecisc** [comment]
Exactly!

**Comment by Bajger** [comment]
I'll issue PR and assign to review.
