### ISSUE TITLE
Where Pharo12?

### ISSUE THREAD

**Issue by privat** [pharo-project/pharo-launcher#598]
Branches and builds from Pharo12 are not listed (maybe this should be automatic and not hard-coded somehow)

**Comment by tesonep** [comment]
I think @demarey has to do his magic in the launcher metadata.
Also, we need to have a green build. 😄

**Comment by privat** [comment]
Seems green enough :) https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/activity?branch=Pharo12

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/activity?branch=Pharo12">Jenkins</a></strong></div></blockquote>

**Comment by demarey** [comment]
Hi @privat 
I just update official template sources.
You just need to restart Pharo Launcher and accept the update of the sources file.
