### ISSUE TITLE
Difference between `quit` button behaviour on Windows and on Linux

### ISSUE THREAD

**Issue by zardoz03** [pharo-project/pharo-launcher#610]
**Describe the bug**
If I were to patch `PharoLauncherApplication>>start` as to autoload settings, and then quit out of the launcher; on Linux the changes would persist, whereas on Windows10, I need to explicitly snapshot the image.

**To Reproduce**
1. Go to Settings, 
2. Expand PharoLauncher tab 
3. Enable Development Environment.
4. open a browser with C-b on PharoLauncherApplication in the opened Playground.
5. Add the following patch to `PharoLauncherApplication>>start`
```diff
    openAsWorld ifTrue: [ 
        self startFull.
        ^ self ].
 
+   ((PhLSettingBrowser new) newTreeHolder) loadSettings.
    
    imagesPresenter open
```
6. Quit the Application.

**Expected behavior**
From using pharo-launcher on Linux, this saved the image state on save. Whereas on Windows I needed to explicitly execute (code below) to get the same behaviour.
```smalltalk
[ (Delay forSeconds: 5) wait.
   Smalltalk snapshot: true andQuit: true 
] fork.
```

**Screenshots**

**Version information:**
 - OS: Windows10+Debian11

**Expected development cost**
I do not know anything of the development effort required as I have not delved into Pharo-Launcher's codebase that extensively.

**Comment by Bajger** [comment]
@zardoz03 Hi! Thanks for reporting ::tada:: Anyway, it is questionable, whether image should be saved, when quitting. I guess not. Application state should be preserved in settings and business code itself should act like any other apps (read-only). If it is different on Win10 and Linux, we should fix it. I vote for to be "quit" action without persisting image state. 
@demarey WDYT?

**Comment by Bajger** [comment]
Meanwhile found this:
```
PhLQuitCommand>>execute
	PhLDownloadManager reset. "reset error logging"
	Smalltalk snapshot: false andQuit: true
```
So intended functionality is to not save image state at all.

**Comment by zardoz03** [comment]
@Bajger after looking at: bde50b825056d14a3e24404caeeb0262ca52a034, the answer must be that I have a pharo-launcher install on my linux machine that was installed before this commit, compared to the one on the windows machine
