### ISSUE TITLE
Cleanup sources

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#612]
The sources of Pharo currently have items that are unreacheable lake the Moose jenkins or the Pharo contribution jenkins. IMO we should remove both. 

Also it might be nice to add: 

```
	PhLTemplateSource {
		#type : #JenkinsServer,
		#name : 'Pharo CI Jenkins',
		#url : 'https://ci.inria.fr/pharo-ci-jenkins2'
	},
```

or

```
PhLTemplateSource {
		#type : #JenkinsServer,
		#name : 'Pharo CI Jenkins',
		#url : 'https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/'
	},
```

For the people working on Pharo development to help reviewing or testing PR artifacts.

**Comment by jecisc** [comment]
I used "bug" category because I find it buggy to show sources that are no reacheable anymore.

**Comment by demarey** [comment]
done in 385628a8ce6e3fb10772525b92d6869443d441bc
