### ISSUE TITLE
Image packaging from CLI throws unhandled exception when path targets directory without write permission

### ISSUE THREAD

**Issue by Bajger** [pharo-project/pharo-launcher#640]
**Describe the bug**
Unhandled exception during packaging image

**To Reproduce**
1. Execute e.g. (or directory with no write permission): `./pharo-launcher image package newImage /home/tmp --zip`
2. See error: 
```
PrimitiveFailed: primitive #createDirectory: in UnixStore failed
UnixStore(ProtoObject)>>primitiveFailed:
UnixStore(ProtoObject)>>primitiveFailed
UnixStore(DiskStore)>>createDirectory:
UnixStore(FileSystemStore)>>ensureCreateDirectory:
UnixStore(FileSystemStore)>>ensureCreateDirectory:
FileSystem>>ensureCreateDirectory:
FileReference>>ensureCreateDirectory
PhLImagePackageCliCommand>>createDirectoryForImageToPack
PhLImagePackageCliCommand>>basicExecute
[ self basicExecute ] in PhLImagePackageCliCommand(PhLCliCommand)>>execute in Block: [ self basicExecute ]
FullBlockClosure(BlockClosure)>>on:do:
PhLImagePackageCliCommand(PhLCliCommand)>>execute
PhLImagePackageCliCommand(ClapApplication)>>executeOrPrintHelp
...
```

**Expected behavior**
User-friendly message is shown to user: "Cannot write to target directory <path-specified-in-arg>. Please check write permissions."

**Version information:**
 - OS: Linux/Ubuntu
 - Version: Pharo-launcher CLI prerelease: https://github.com/pharo-project/pharo-launcher/actions/runs/7501196046

**Expected development cost**
Add handing of exception to: `PhLImagePackageCliCommand>>createDirectoryForImageToPack`

**Comment by demarey** [comment]
Also, for error handlng, probably Pharo Lzuncher CLI should handle all exceptions to only provide the error message and not the full stack (with an option to display the full stack)
