### ISSUE TITLE
Scripts to run Pharo Launcher aren't executable by default

### ISSUE THREAD

**Issue by Bajger** [pharo-project/pharo-launcher#641]
**Describe the bug**
Scripts to run Pharo Launcher aren't executable by default: `pharo-launcher` and `pharo-launcher-ui`

**To Reproduce**
1. Go to directory with deployed launcher package.
2. Execute e.g.: `./pharo-launcher help`
3. See error: `bash: ./pharo-launcher: Permission denied`
4. Same for `pharo-launcher-ui`

**Expected behavior**
Both executable scripts should be set to be executable by default. 

**Screenshots**

**Version information:**
 - OS: Linux/Ubuntu
 - Version: Pre-release: https://github.com/pharo-project/pharo-launcher/actions/runs/7501196046

**Expected development cost**
Add `chmod`to set executable flag on both scripts.

**Comment by demarey** [comment]
After a fresh git clone, both scripts have execution permissions.
It looks loke github artifact archive loose these permissions: https://github.com/actions/upload-artifact/issues/38
