### ISSUE TITLE
Path to Launcher VM is incorrectly set in execution scripts of Pharo launcher

### ISSUE THREAD

**Issue by Bajger** [pharo-project/pharo-launcher#642]
**Describe the bug**
Execution scripts `pharo-launcher` and `pharo-launcher-ui` has wrong path to launcher vm. 

**To Reproduce**
1. Go to directory with unpacked pharo-launcher package
2. Execute e.g.: `./pharo-launcher help`
3. See error: `./pharo-launcher: line 33: ./pharo-vm/pharo: No such file or directory`
Reason: Pharo vm is currently `./shared/pharo-vm/pharo`

**Expected behavior**
Launcher scripts (UI as well as CLI) points to correct vm path and can be successfully executed. 

**Version information:**
 - OS: Linux/Ubuntu
 - Version: https://github.com/pharo-project/pharo-launcher/actions/runs/7501196046

**Expected development cost**
Either vm is moved to `pharo-vm` (instead of `shared/pharo-vm`) during packaging.
Or scripts are adopted to use `./shared/pharo-vm` instead of `pharo-vm`

**Comment by demarey** [comment]
yes, it looks like `pharo-vm` is wrongly put into the `shared` directory.
