### ISSUE TITLE
Rename command processList

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#655]
processList is not the nicest name
we should find a better name for it

**Comment by Bajger** [comment]
Candidates:
`pharo-launcher image running` 
`pharo launcher image processes`
`pharo launcher image process`

or all image process related cmds to factor into separate command:
`pharo-launcher process list`
`pharo-launcher process kill`

Thoughts?

**Comment by Ducasse** [comment]
running is nice 
now process is nice too. 

BTW the presentation of Christophe shows that plcli is cool :) tx for your help and commitment there.

**Comment by Ducasse** [comment]
In fact process can be better :)

**Comment by demarey** [comment]
yes, I also like process list / kill
