### ISSUE TITLE
Command line - One should be able to specify the default version

### ISSUE THREAD

**Issue by jordanmontt** [pharo-project/pharo-launcher#664]
Some people use the dev version as the default one. So, instead of doing `$ pharo-launcher image create -dev newImage`, one could say that the default is always dev

**Comment by guillep** [comment]
It looks like you want peolpe to give their own short names

**Comment by jordanmontt** [comment]
I mean when I do `$ pharo-launcher image create newImage`, currently it downloads the Stable version. I would like to be able to specify which is the "default image" to download. For example, I almost always download the development version. So, instead of writing `-dev`  all the time, I would like to configure that when I do `$ pharo-launcher image create newImage` it downloads dev instead of Stable
