### ISSUE TITLE
Why cannot select more than one template to download/create image?

### ISSUE THREAD

**Issue by hernanmd** [pharo-project/pharo-launcher#668]
Any special reason why I couldn't create more than one image from the template list?

**Screenshots**
<img width="889" alt="Screenshot 2024-01-30 at 12 38 06" src="https://github.com/pharo-project/pharo-launcher/assets/4825959/5cb09213-9d6c-4dbc-93bc-3b5588379753">

**Comment by demarey** [comment]
Because you have to provide the image name for each new image. And it is the first time someone ask for this use case.

**Comment by hernanmd** [comment]
Thanks. I will check if it's easy to do it since AFAIK that would required another button "Download image(s)" next to the "Create image" right?
Or to make a contextual menu?
What do you think?

**Comment by demarey** [comment]
IMO, this feature is not a core feature. I even do not have a scenario for it. I would not even add it.
Do you have a scenario in mind?

**Comment by hernanmd** [comment]
> IMO, this feature is not a core feature. I even do not have a scenario for it. I would not even add it. Do you have a scenario in mind?

Yes, find offending commits for instance.

There were already a request for it in Pharo Launcher: https://github.com/pharo-project/pharo-launcher/issues/6
And there is an article expaining the tedious manual labor process: https://thepharo.dev/2020/11/23/bisecting-pharo-versions-to-find-regressions/

It is important to realize that there is more than a single use case for the Pharo Launcher. Many times you want to automate tasks with several images, for example 

1) To measure the performance of execution between images over a period of time. 
2) Or compare how the size of the images has grown.

I think it is not a big modification (in the UI it would be just a menu button/option and a beMultiselection).


<blockquote><img src="https://masteringobjects.files.wordpress.com/2020/10/image.png" width="48" align="right"><div><img src="https://masteringobjects.files.wordpress.com/2020/03/cropped-icon-lighthouse-512x512-1-1.png?w=192" height="14"> The Pharo Dev: Mastering Objects</div><div><strong><a href="https://thepharo.dev/2020/11/23/bisecting-pharo-versions-to-find-regressions/">Bisecting Pharo versions to find regressions</a></strong></div><div>From time to time it happens that a bug is accidentally introduced and we realize it several versions later. If the cause of the bug is not clear, one good strategy is to find the piece of code cha…</div></blockquote>

**Comment by demarey** [comment]
I already started a bisect feature for Pharo Launcher a few days ago.
You will provide it an interval (from build X to build Y) and it will run a script that should evaluate to a boolean.
Don't you think it will be enough?

**Comment by guillep** [comment]
> I already started a bisect feature for Pharo Launcher a few days ago. You will provide it an interval (from build X to build Y) and it will run a script that should evaluate to a boolean. Don't you think it will be enough?

Neat! 
Later you will show me, maybe this could serve as a first step towards an interactive bisect.
Some properties to test/assess when bisecting are difficult to express simply in code (e.g., is there a scroll bar in X window after I click on Y?). Anyways, it's not for now, I can continue to do it manually when I have such a case :)

**Comment by demarey** [comment]
yes, you're right, an interactive bisect would also be needed. I nthis case, you will have to give the ok or ko by yourself

**Comment by hernanmd** [comment]
> I already started a bisect feature for Pharo Launcher a few days ago. You will provide it an interval (from build X to build Y) and it will run a script that should evaluate to a boolean. Don't you think it will be enough?

That would be really nice.
Please let us know which branch you're working on, or if you want to show us a demo/video, etc.

**Comment by demarey** [comment]
Interactive bisect is now implemented in 56b7b79cd38bd68ed573c991df7bfdbf053dce7d.
I will close this issue.
