### ISSUE TITLE
File ‘sources.list’ on ‘files.pharo.org’ is not up-to-date

### ISSUE THREAD

**Issue by Rinzwind** [pharo-project/pharo-launcher#678]
The [file ‘sources.list’ hosted on ‘files.pharo.org’](https://files.pharo.org/pharo-launcher/sources.list) (URL used in [`#defaultSourcesUrl` for PhLPharoTemplateSources](https://github.com/pharo-project/pharo-launcher/blob/928adbd4d41439621b50be85e6c56c0c523081d8/src/PharoLauncher-Core/PhLPharoTemplateSources.class.st#L57-L60)) doesn’t seem to be up-to-date, it specifically does not include the changes of pull request #670.

**Comment by demarey** [comment]
Thank you for the report!
Good catch!
I just updated it.
Thank you
