### ISSUE TITLE
Downloading from ‘pharo.org’ downloads v3.0.1 rather than v3.1.1

### ISSUE THREAD

**Issue by Rinzwind** [pharo-project/pharo-launcher#679]
The comment for [release 3.1.1](https://github.com/pharo-project/pharo-launcher/releases/tag/3.1.1) says “the prefered way is to download signed and notarized installers from [https://pharo.org/download](https://pharo.org/download)”, but downloading from the latter downloads v3.0.1 (when using the link ‘MacOs x64’ at least).

**Comment by demarey** [comment]
Hi
Thank you for the report.
Indeed, release 3.1.1 is not a "real" release but was used to setup the CI on github.
The last stable release is still 3.0.1
A new release should come soon.
