### ISSUE TITLE
List of templates in the category ‘Pharo 12.0 (stable)’ does not include the builds after build 1258

### ISSUE THREAD

**Issue by Rinzwind** [pharo-project/pharo-launcher#683]
The template category ‘Pharo 12.0 (stable)’ does not include the builds after build 1258:

<p align="center">
<img width="488" src="https://github.com/pharo-project/pharo-launcher/assets/1611248/3a3f0964-a5d6-4ae3-bf5e-ba5fca9fd46c">
</p>

Similar earlier issue: issue #667.

**Comment by demarey** [comment]
Thank you for the report. 
I forgot to update the regex for the new stable image. Image filename changed during P12 development.
