### ISSUE TITLE
Import command should delete origin folder if empty

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#70]
Often you want to import an image freshly downloaded. The folder will only contains a .image and .changes. 

It could be cool to check if the origin folder is empty after the import and delete it in that case.

**Comment by demarey** [comment]
yes, good idea.

---

Name: PharoLauncher-Core-ChristopheDemarey.172
Author: ChristopheDemarey
Time: 20 January 2018, 9:19:11.295011 pm
UUID: c28c9fa5-9c1f-0d00-81bc-22e80a678d3a
Ancestors: PharoLauncher-Core-ChristopheDemarey.171

Do not import if a directory is selected.
Remove parent folder if empty after import.

https://github.com/pharo-project/pharo-launcher/issues/70

**Comment by jecisc** [comment]
@demarey Thank you for this quick feature implementation :)
