### ISSUE TITLE
Disable Cmd-Dot for release images

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-project/pharo-launcher#72]
Hello,

It is possible to disable the shortcut to open the debugger like this:
```
UserInterruptHandler cmdDotEnabled: false.
```

Shouldn't it be done?

**Comment by demarey** [comment]
it could.
not really a problem if it is not disabled (nothing to hide).

**Comment by jecisc** [comment]
I think this is cool for obfuscation. But PharoLauncher does not need obfuscation. And since it is a tool for developers and not end users, I don't see what would be the advantage to block Cmd-Dot. 

Maybe I am missing something :)

**Comment by demarey** [comment]
yes, I have the same feeling as you Cyril.

**Comment by juliendelplanque** [comment]
I see, I just thought we should not let someone do it because then the user could does something bad to the image no?

But I agree, the users should only be developers so... :-)
