### ISSUE TITLE
Managers of Download of VMs and images should be in their own packages

### ISSUE THREAD

**Issue by VincentBlondeau** [pharo-project/pharo-launcher#73]
The goal being to reuse them in another project without loading all the launcher

**Comment by demarey** [comment]
yes, we could.
Just to let you know, we have a plan to make a pharo launcher version usable with the command line

**Comment by VincentBlondeau** [comment]
Ok. But I just want to cut a part to reuse in another project without loading all. I will do the changes on the monticello repository then.

**Comment by demarey** [comment]
Yes, feel free to do it. I hope there are no dependencies on other PharoLauncher classes (should be ok for VMs but not sure for images)

**Comment by VincentBlondeau** [comment]
Committed. Added a new 1.2 baseline version
