### ISSUE TITLE
version 1.1 does not run in Mac OS - 10.13.3

### ISSUE THREAD

**Issue by akevalion** [pharo-project/pharo-launcher#77]
OS Version
Mac OS - 10.13.3
version 1.1
http://files.pharo.org/pharo-launcher/1.1/

1. Load P.L version 1.1
2. Copy the application in `Applications` folder
3. Try to open the program, with right-click, open
4. Current result the program P.L. does not run.

If this version is not stable for mac maybe you need to hide this file from the url

**Comment by demarey** [comment]
Thanks for the report.
Did you follow installation instructions at http://pharo.org/download ?
>  Mac OS X: Double-click on the dmg file and drop Pharo Launcher app in Applications folder. Before being able to run Pharo Launcher, you may need to update temporarily your security settings: if you have Mac OS X 10.8 or higher then you might get a message saying that Pharo "can’t be opened because it is from an unidentified developer". This is due to the OS X Gatekeeper feature that is designed to discourage users from downloading from random locations and possibly installing something bad. Assuming you've downloaded Pharo Launcher from Pharo web site, then you have nothing to worry about, and you just need to bypass this warning:
> - Recommended - Right click (or command+click) the application icon and select "open"
> - Advanced - Enable all application downloads
>   -  In OS X go to the Apple Menu -> System Preferences -> Security & Privacy -> General ->
>   -   Unlock the padlock at the bottom of the window, which will require a computer admin password
>   -  Where it says "Allow applications downloaded from:" select "Anywhere"
>   -  OS X will give you a scary warning that is a bit exaggerated. If you're not comfortable with this, use the "right click" method mentioned above. In all cases OS X will still ask you if you want to open an "unsigned" application the first time it is opened, so new applications that are downloaded can't just start by themselves.

**Comment by akevalion** [comment]
Yes, I did it

**Comment by demarey** [comment]
Another guess about the error. Did you only try to open it once? If so, could you try to open it a second time?

There is a strange behaviour with OS X Gatekeeper and file quarantine. Once quarantine flag is removed from Pharo Launcher app, it should open

**Comment by demarey** [comment]
Version 1.4.6 is now out. Please test it. If you still have an issue, please reopen the issue
