### ISSUE TITLE
PharoLauncher 1.1 x64 - Official Distributions loads 32bit versions on 64bit System

### ISSUE THREAD

**Issue by sasiflo** [pharo-project/pharo-launcher#82]
The PharoLauncher 1.1 x64 from the pharo.org download page loads 32bit VM when creating images from the node "Official distributions" on Linux 64bit.

![grafik](https://user-images.githubusercontent.com/1850927/38169053-843a4e10-355f-11e8-9de8-892f66daaa75.png)
When starting "Pharo 6.1" or "Pharo 7.0" - created from "Official distributions" an error occured and Pharo aborts.
![grafik](https://user-images.githubusercontent.com/1850927/38169072-08a92540-3560-11e8-9688-1b44e8012e5e.png)

**Comment by sasiflo** [comment]
Ok, see the problem now.

PharoLauncher does not automatically distinguish the image to load depending on the platform.

So solution must be, to add 64bit versions to "Official distributions". Have not found where the content of the groups came from.

**Comment by sasiflo** [comment]
Sorry, don't know how to contribute with Monticello. But have a file that could help. I am totally used to github.
[PharoLauncher-Core-sasiflo.170(ChristopheDemarey.169).mcd.zip](https://github.com/pharo-project/pharo-launcher/files/1866368/PharoLauncher-Core-sasiflo.170.ChristopheDemarey.169.mcd.zip)

**Comment by Ducasse** [comment]
Do not use mcd, better send a full mcz file.
I think that christophe is migrating to github.

**Comment by sasiflo** [comment]
Ok, hope this is the correct file:


[PharoLauncher-Core-sasiflo.170.mcz.zip](https://github.com/pharo-project/pharo-launcher/files/1866395/PharoLauncher-Core-sasiflo.170.mcz.zip)

**Comment by demarey** [comment]
Hi,

The current behaviour of PharoLauncher is the one we wanted to have: Pharo Launcher allows you to work either with 32-bits either with 64-bits Pharo images. Accordingly, PharoLauncher downloads the appropriate VM (32-bits or 64-bits).
There is no official support for Pharo 6.1 64-bits images. it is only a preview. Official 64-bits support will start with Pharo 7.

Nevertheless, it is right architecture info is missing in images descriptions.
Thanks for the contribution.
It is now commited in PharoLauncher repository: 
```
Name: PharoLauncher-Core-ChristopheDemarey.176
Author: ChristopheDemarey
Time: 3 April 2018, 9:20:35.475099 am
UUID: 8d138f47-4e25-0d00-b977-214c06d79741
Ancestors: PharoLauncher-Core-VincentBlondeau.175, PharoLauncher-Core-sasiflo.170

Add 32 - 64-bits into image description.
See https://github.com/pharo-project/pharo-launcher/issues/82.
Contribution from sasiflo.
```
