### ISSUE TITLE
64-bit as first-class citizen

### ISSUE THREAD

**Issue by pjgoodall** [pharo-project/pharo-launcher#83]
Much like the 32-bit (and perhaps labeling them as 32-bit them too), can we please have  distinguished 64-bit categories for (stable, development) x ([version]) as categories on the main list.

Thanks for this very useful tool.

Cheers,
--Peter G

**Comment by demarey** [comment]
Hi Peter,

Good idea! For now, there is no official / stable Pharo 64-bits image (the first one will be Pharo 7.0).
In https://github.com/pharo-project/pharo-launcher/issues/82, we improved the situation by providing info on the image architecture. Maybe a 64-bits category will be needed in the future?
Does the previous fix is enough for now?

**Comment by demarey** [comment]
@pjgoodall Could you tell me if #82 fix is enough to close this issue?

**Comment by demarey** [comment]
no news. Please consider to re-open the issue if you think it is still valid
