### ISSUE TITLE
Sort Existing Images Case-Insensitive

### ISSUE THREAD

**Issue by seandenigris** [pharo-project/pharo-launcher#86]
It's easy to get confused when `aaa` image shows up at the end of a potentially long list. The change is simple:
```smalltalk
PhLDirectoryBasedImageRepository>>#roots
	^ self images sorted: [ :i1 :i2 | i1 name asUppercase < i2 name asUppercase ]
```

Should I commit directly to StHub? If so, I don't remember, can I save off whatever ancestor is in my image and MC will be smart enough to rebase into latest when you merge, or do I need to dl an updated Launcher and then commit?

**Comment by demarey** [comment]
Hi Sean,

Yes, good idea. You could have committed directly to SH. Merge is not a problem.
As the fix is really simple, I committed it directly on top of the latest version:
```
Name: PharoLauncher-Core-ChristopheDemarey.183
Author: ChristopheDemarey
Time: 10 April 2018, 8:41:35.187389 am
UUID: 7ebff48c-da25-0d00-9492-7bfd058b48e2
Ancestors: PharoLauncher-Core-ChristopheDemarey.182

Sort Existing Images Case-Insensitive #86
https://github.com/pharo-project/pharo-launcher/issues/86
```
Thanks for the enhancement.
