### ISSUE TITLE
 Pharo Launcher on Windows > Failing

### ISSUE THREAD

**Issue by philippeback** [pharo-project/pharo-launcher#88]
I wanted to try Pharo Laucher before the tech talk
 
But I get this when asking for an image
 
![image002](https://user-images.githubusercontent.com/2128441/38690588-bfdf3d4a-3e7e-11e8-85ef-ed142ad02da1.png)

**Comment by philippeback** [comment]
[PharoDebug.log](https://github.com/pharo-project/pharo-launcher/files/1904107/PharoDebug.log)

For some reason there is no fuel out stack in the debugger.

![image](https://user-images.githubusercontent.com/2128441/38690719-18f635f0-3e7f-11e8-849a-64e1d3a273e0.png)

**Comment by philippeback** [comment]
![image](https://user-images.githubusercontent.com/2128441/38690767-33d47b20-3e7f-11e8-9edc-a2d70a7cf948.png)

folder is indeed empty

![image](https://user-images.githubusercontent.com/2128441/38690812-52ac2be2-3e7f-11e8-99a2-51036ebcc83a.png)

but there are VMs one level above.

![image](https://user-images.githubusercontent.com/2128441/38690834-626d9f7a-3e7f-11e8-80f8-32c60face2e9.png)

**Comment by philippeback** [comment]
![image](https://user-images.githubusercontent.com/2128441/38690886-872e947c-3e7f-11e8-8779-fccedf149409.png)

**Comment by VincentBlondeau** [comment]
Thanks for the stack it was very helpful!
I succeeded to identify and fix the issue:

```
Name: PharoLauncher-Download-VincentBlondeau.10
Author: VincentBlondeau
Time: 12 April 2018, 5:36:42.369656 pm
UUID: 90fa90cd-1126-0d00-8273-e9b70cdf30bf
Ancestors: PharoLauncher-Download-ChristopheDemarey.9

- Add a cleaning of the vm/private folder in case of error (solve https://github.com/pharo-project/pharo-launcher/issues/88)
- Add new exception if the executable is not found inside the folder
- Minor code cleaning
```

You will have to load the bleeding edge version to get the fix.
However, if you want a quick fix, you could just delete the contents of the private folder.

**Comment by philippeback** [comment]
How do I load the bleeding edge? Just load from Monticello once I have accessed the devtools?

**Comment by demarey** [comment]
Hi Phil,

Thank you for the bug report. And thanks to Vincent for fixing it!
You can get a fresh version of Pharo Launcher from http://files.pharo.org/pharo-launcher/bleedingEdge/. I just disabled the 64-bits version for now because it fails too often and is annoying when we develop Pharo Launcher. Anyway, just update packages from Monticello and save the image should work (use cmd+w shortcut to get a playground and call Smalltalk snapshot:andQuit:).

**Comment by philippeback** [comment]
Hi,

It works nicely now, with a nice icon and all.

The best thing is not that it just works, but that the VM+image downloaded
work nicely on a 4K UHD screen without having a small quarter sized window
in a large window as it was for a few VM versions past.

System reporter gives for this 6.1 under Windows 10 with the bleeding edge
Pharo Launcher asking for a 32 bits image:

Image
-----
C:\Users\phil\Documents\Pharo\images\Pharo 6.1 - 32bit
(stable)\Pharo61-Phil.image
Pharo6.0
Latest update: #60540
Unnamed

Virtual Machine
---------------
C:\Users\phil\Documents\Pharo\vms\61-x86\Pharo.exe
CoInterpreter VMMaker.oscog-eem.2254 uuid:
4f2c2cce-f4a2-469a-93f1-97ed941df0ad Jul 20 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid:
2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 20 2017
VM: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
Date: Thu Jul 20 12:42:21 2017 -0700 $ Plugins: 201707201942
https://github.com/OpenSmalltalk/opensmalltalk-vm.git $

Win32 built on Jul 20 2017 20:21:26 GMT Compiler: 5.4.0
VMMaker versionString VM: 201707201942
https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Thu Jul 20
12:42:21 2017 -0700 $ Plugins: 201707201942
https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
CoInterpreter VMMaker.oscog-eem.2254 uuid:
4f2c2cce-f4a2-469a-93f1-97ed941df0ad Jul 20 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid:
2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 20 2017

Ah! Now this is looking like a usable cool thingy. Sweet!
Also noticed that it installs itself in a better location. That's double
nice.

Thx for the  launcher, seems well deserved.

Phil
