### ISSUE TITLE
Disable preferences by default

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#91]
It would be cool to disable preferences loading by default in PharoLauncher. And maybe make it a preference in the launcher settings. 

In Pharo 7 it can be done via: 

PharoCommandLineHandler class>>forcePreferencesOmission

What do you think? (maybe not for the current version if it needs to be Pharo 6 compatible)

**Comment by demarey** [comment]
Hi Cyril,

What do you mean? Preferences for the Pharo Laucnher or for launched images?

**Comment by jecisc** [comment]
Pharo preferences. 

When I install the launcher and launch it for the first time my Pharo preferences does not load. But if I close it and launch it again, my Pharo preferences are loaded.

**Comment by demarey** [comment]
strange. PharoLauncher now has its own settings and do (should) not load default pharo settings. You can take a look at `PhLSettingsBrowser>>#launcherStartUp`.

Also, startup preferences are disabled for PharoLauncher:
```
PharoCommandLineHandler>>#runPreferences
	"When Pharo Launcher is deployed, ignore Pharo preferences. Pharo preferences will only be loaded when Pharo Launcher is in developer mode."
	"PhLSettingBrowser startup action is in charge of loading launcher preferences."
	PhLDeploymentScript isDeployed ifTrue: [ ^ self ].
	
	Smalltalk at: #SystemSettingsPersistence ifPresent: [:persistence | 
		persistence resumeSystemSettings ].
	Smalltalk at: #StartupPreferencesLoader ifPresent: [:loader |
		loader default loadFromDefaultLocations ].
```
Could you add some logging to see what is executed?

**Comment by jecisc** [comment]
When I'll have some time I'll try to reinstall and log.

**Comment by jecisc** [comment]
Ok, I found my problem. It's because I changed the deployment setting :)
Sorry for the noise.
