### ISSUE TITLE
Images do not launch - Linux Mint 64 bit

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-launcher#94]
From the mailing list:

>I just downloaded the Linux 64bit version of Pharo from the web site:
>
>-> I opened "pharo" (via a double click on the pharo application) and
got a list of possible templates I could load.
>
>-> I selected Pharo 6.1 template, created an image and wanted to start
that image - the initial application disappeared - but nothing happened
after that.
>
>If I start the initial pharo app from a shell by hand and I want to
start the selected image it seems to work.
>
>My system: Linux Mint 18.1, 64 bit

**Comment by franciscoLizarralde** [comment]
I experienced the same with the Linux 64bit version of Pharo and Ubuntu 18.04 64 bit.

I got this message.

Try this on a terminal:

cd "/home/francisco/Pharo/vms/private/6521" && export SQUEAK_PLUGINS="" &&
"/home/francisco/Pharo/vms/private/6521/pharo" --nodisplay
"/home/francisco/Pharo/images/Pharo 6.1 (stable)_1/Pharo 6.1
(stable)_1.image" eval "(Smalltalk imagePath asFileReference parent) /
'pharo.version' writeStreamDo: [ :stream | |major minor|major :=
SystemVersion current major.minor := SystemVersion current minor.(major = 6
and: [ SystemVersion current highestUpdate >= 60509 ])ifTrue: [ minor := 1
].stream << major asString;<< minor asString ]"

And got this:

Error. Could not determine platform's libc path for VM.
Try forcing $PLATFORMLIBDIR in /home/francisco/Pharo/vms/private/6521/pharo,
based on LIBC_SO.
Please report what works to pharo [vm-dev] mail list.
  LIBC_SO=
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=18.04
  DISTRIB_CODENAME=bionic
  DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
  NAME="Ubuntu"
  VERSION="18.04 LTS (Bionic Beaver)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 18.04 LTS"
  VERSION_ID="18.04"
  VERSION_CODENAME=bionic
  UBUNTU_CODENAME=bionic
  UNAME=Linux Dynabook 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17
UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  System seems to be 64 bit. You may need to (re)install the 32-bit
libraries.

**Comment by demarey** [comment]
In fact, the problem comes from launching a 32-bit image requiring a 32-bit VM on 64-bit system not having 32-bit libraries installed.
See #112 .
I will close this issue as the other explains better the problem.
