### ISSUE TITLE
Launcher does not open if launched images are not killed - OSX

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-launcher#95]
From mailing list

> That's the way I work as well, especially because I found that on Mac
> apparently you have to close all open images before Launcher will open again
> from the Dock.
>

**Comment by demarey** [comment]
We cannot do anything for that. It is how OS X works. PharoLauncher and Pharo images use the same executable.
One can still open PharoLauncher by using `open -n PharoLauncher.app`

**Comment by guillep** [comment]
I don't understand. That is indeed a bug. Even if below they have the same executable, they should be independent.

Otherwise, how do Java apps do work?

**Comment by demarey** [comment]
one point for you.
So maybe there is a solution to work-around that.
I guess it should be something to tune in plist file to declare different apps.

**Comment by demarey** [comment]
fixed in current version
