### ISSUE TITLE
Image version determination error

### ISSUE THREAD

**Issue by ivansc11** [pharo-project/pharo-launcher#97]
Can't open any image version. This is what pops up.

Cannot determine image version: image version file not found!
Try to run this command in a shell to get more information on the problem:
cd "F:\Pharo" && "F:\Pharo\Pharo.exe" --headless "C:\Users\Ivan\Documents\Pharo\images\Pharo 5.0\Pharo 5.0.image" eval "(Smalltalk imagePath asFileReference parent) / 'pharo.version' 		writeStreamDo: [ :stream | |major minor|			major := SystemVersion current major.			minor := SystemVersion current minor.			(major = 6 and: [ SystemVersion current highestUpdate >= 60509 ])				ifTrue: [ minor := 1 ].			stream 				<< major asString;				<< minor asString ]"
sd

**Comment by ivansc11** [comment]
![capture](https://user-images.githubusercontent.com/38736081/39269091-36429a94-48a8-11e8-9bc6-e1ed3b677100.PNG)

**Comment by demarey** [comment]
Thanks for the report.
To help me figure out what happens, could you execute the given command in a shell (cmd.exe) and send the output?

**Comment by ivansc11** [comment]
sorry, i had a nasty malware that prevented me to open cmd, formatted and now works like a charm. sorry again.

**Comment by VincentBlondeau** [comment]
Thanks @ivansc11!  I close the bug entry in this case
