### ISSUE TITLE
Copy and subfolders problem (contents no copied)

### ISSUE THREAD

**Issue by philippeback** [pharo-project/pharo-launcher#98]
In the Pharo Launcher (Windows 19 here), I do a copy of an existing "image" (actually an entry in the right pane).

The copy copies everything which is at the root and the subfolders but the subfolders end up being empty (apparently pharo-local and github-cache included).

That's pretty annoying and makes the copy feature a lot less interesting.

**Comment by VincentBlondeau** [comment]
it should be much more interesting with that ;) :

Name: PharoLauncher-Core-VincentBlondeau.188


Author: VincentBlondeau
Time: 24 May 2018, 1:27:53.042507 pm
UUID: 4b4a0b39-5b29-0d00-94d5-c77a047b713a
Ancestors: PharoLauncher-Core-VincentBlondeau.187

copy now copy all the contents of the image folder and renaming is much more faster because does not imply a copy but just a moveTo: and a renaming

**Comment by philippeback** [comment]
That's great news. Thx a lot. I'll check that out.

**Comment by demarey** [comment]
This fix will be good for Phil use case but it is a regression for other use cases.
By example, I use this feature to copy an image that is in a folder with a lot of other things. I do not want to move everything!
We should introduce a dialog box to ask what to do?
- only import image, sources, and pharo-local folder
- or move the parent folder

**Comment by philippeback** [comment]
And then if I have a lot of other things, I want them to move with the image (CSS, resources, doc, ...).

Now I also use https://github.com/Pharophile/HOImageSaver and am looking into how to support that in the Launcher (like having a menu entry showing me all the datetime saves, so that I can pick one, because sometimes, Pharo freezes badly or I do something super silly, and going through the motions of copying the image is not really helping with the flow).

**Comment by demarey** [comment]
> And then if I have a lot of other things, I want them to move with the image (CSS, resources, doc, ...).
Movving the parent folder of the image does not fit your need in this case?

Guille planned to switch from MorphTreeMorph to FTTree to render the liste of images. With that, the idea is to display more properties in the image list, especially the last modification time and enable sort on this property. Would it be enough for your use case?

**Comment by philippeback** [comment]
No, not good enough. Say I have a sample web app with all kind of things on the side, including sqlite db.

I want to clone this with everything for a demo for example, of for fixing a bug in isolation.

**Comment by demarey** [comment]
To be discussed with other people, but to me it could be added to the PharoLauncher. Your code is quite small and the functionality could be useful.
I you want to experiment, you could subclass #PhLCopyImageCommand. With less than 10 lines of code, you should get what you want.

**Comment by philippeback** [comment]
Ok, will look into that.

**Comment by demarey** [comment]
> This fix will be good for Phil use case but it is a regression for other use cases.
By example, I use this feature to copy an image that is in a folder with a lot of other things. I do not want to move everything!
We should introduce a dialog box to ask what to do?
>-  only import image, sources, and pharo-local folder
>-  or move the parent folder

I now understand that this concern was not well understood. When writing that, I had the import command in mind whereas we are talking on the copy command! I agree that we should always copy everything for the copy command.
I also implemented 2 different imports: import image, changes and pharo-local files or import the full image directory.
